extends Node

signal damage_about_to_apply(damage_info: Variant, target: Node)
signal damage_applied(damage_info: Variant, target: Node, final_amount: float)
signal hit_confirmed(damage_info: Variant, target: Node, final_amount: float)
signal entity_died(entity: Node, killer: Variant)
signal room_started(run_id: String, room_id: StringName, revision: int)
signal room_cleared(run_id: String, room_id: StringName, revision: int)
signal reward_selected(run_id: String, definition: Dictionary, revision: int)
signal time_skill_started(skill_id: StringName, context: Dictionary)
signal time_skill_ended(skill_id: StringName, context: Dictionary)
signal player_dashed(context: Dictionary)
signal player_attacked(weapon_id: StringName, context: Dictionary)
signal enemy_spawned(enemy: Node, context: Dictionary)
signal run_started(run_id: String, snapshot: Dictionary)
signal run_ended(run_id: String, result: Dictionary, revision: int)
