extends Node

signal damage_about_to_apply(damage_info: Variant, target: Node)
signal damage_applied(damage_info: Variant, target: Node, final_amount: float)
signal hit_confirmed(damage_info: Variant, target: Node, final_amount: float)
signal entity_died(entity: Node, killer: Variant)
signal room_started(run_id: String, room_id: StringName, revision: int)
signal room_cleared(run_id: String, room_id: StringName, revision: int)
signal route_selected(run_id: String, floor_id: StringName, edge_id: StringName, destination_node_id: StringName, revision: int)
signal floor_started(run_id: String, floor_id: StringName, floor_index: int, revision: int)
signal floor_completed(run_id: String, floor_id: StringName, floor_index: int, revision: int)
signal reward_selected(run_id: String, definition: Dictionary, revision: int)
signal time_skill_started(skill_id: StringName, context: Dictionary)
signal time_skill_ended(skill_id: StringName, context: Dictionary)
signal time_skill_committed(ability_id: StringName, token: int, generation: int, frame: int, run_id: StringName, context: Dictionary)
signal player_dashed(context: Dictionary)
signal weapon_action_committed(weapon_id: StringName, action_id: StringName, token: int, context: Dictionary)
signal weapon_cue_requested(weapon_id: StringName, action_id: StringName, token: int, cue: Dictionary)
signal weapon_resource_changed(weapon_id: StringName, resource_id: StringName, current: float, maximum: float, reason: StringName)
signal weapon_hit_confirmed(weapon_id: StringName, action_id: StringName, token: int, target_id: int, context: Dictionary)
signal weapon_mastery_confirmed(weapon_id: StringName, mastery_family: StringName, mastery_id: StringName, action_id: StringName, token: int, generation: int, target_id: int, context: Dictionary)
signal enemy_spawned(enemy: Node, context: Dictionary)
signal run_started(run_id: String, snapshot: Dictionary)
signal run_ended(run_id: String, result: Dictionary, revision: int)
