#!/usr/bin/env python3
"""Generate the first deterministic Plane Walker UI/gameplay art slice.

The source is intentionally small and offline.  It produces pixel-aligned
weapon, time-ability and player-effect atlases, then records those assets and
the already certified actor/enemy/room batches in one inventory manifest.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from functools import lru_cache
from pathlib import Path
from typing import Iterable

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "assets" / "production" / "ui"
FRAME_SIZE = 32
FRAME_COUNT = 4
PALETTE = {
    "ink": (17, 22, 25, 255),
    "stone": (36, 45, 45, 255),
    "edge": (105, 119, 113, 255),
    "bone": (237, 240, 220, 255),
    "muted": (171, 184, 172, 255),
    "patina": (121, 186, 161, 255),
    "time": (97, 213, 231, 255),
    "brass": (229, 189, 105, 255),
    "danger": (240, 112, 101, 255),
    "ember": (223, 155, 101, 255),
    "void": (184, 151, 215, 255),
    "time_shadow": (44, 141, 160, 255),
    "brass_shadow": (164, 119, 62, 255),
    "void_shadow": (118, 87, 154, 255),
    "danger_shadow": (169, 70, 79, 255),
}

WEAPONS = ("sword", "bow", "gun", "staff", "gauntlets")
ABILITIES = ("stop", "rewind", "accelerate", "rift")
EFFECTS = ("weapon_arc", "arrow_trail", "muzzle_flash", "spell_burst", "time_ring", "rift_bloom")
PROJECTILES = ("arrow", "bullet", "staff_arcane", "staff_fire", "staff_ice", "staff_lightning")
CONTENT_SOURCES = {
    "items": ROOT / "data" / "content_packs" / "base" / "content" / "items.json",
    "blessings": ROOT / "data" / "content_packs" / "base" / "content" / "blessings.json",
    "curses": ROOT / "data" / "content_packs" / "base" / "content" / "curses.json",
    "talents": ROOT / "data" / "content_packs" / "base" / "content" / "talents.json",
}
CONTENT_METADATA = {category: {row["id"]: row for row in json.loads(path.read_text())}
                    for category, path in CONTENT_SOURCES.items()}
MODE_ART = ("boss_rush", "daily_boss", "authored_challenges", "training", "endless")
ROOM_TYPES = ("entry", "unknown", "combat", "elite", "treasure", "shop", "event", "boss", "rest")
EVENT_IDS = tuple(row["id"] for row in json.loads((ROOT / "data/content_packs/base/content/dungeon_events.json").read_text()))
NARRATIVE_ROWS = json.loads((ROOT / "data/content_packs/base/content/narrative_definitions.json").read_text())
NPC_IDS = tuple(row["npc_id"] for row in NARRATIVE_ROWS if row["definition_kind"] == "npc")
ENDING_IDS = tuple(row["ending_id"] for row in NARRATIVE_ROWS if row["definition_kind"] == "ending")
REWARD_ROWS = json.loads((ROOT / "assets/production/modes/challenge_rewards.json").read_text())["rewards"]
REWARD_IDS = tuple(row["id"] for row in REWARD_ROWS)
CONTROLS = ("decline_contract", "play", "pause", "copy", "paste", "export", "delete", "back", "settings", "bindings", "restart", "quit", "build", "import", "refresh", "next", "screenshot", "account", "storage", "community", "content", "sharing")
UI_FRAMES = ("panel", "panel_active", "panel_danger", "divider", "badge", "cursor", "chrome_panel", "chrome_button", "chrome_focus")

LICENSE = """Plane Walker Original UI Art Slice

The weapon, time-ability, player-effect, projectile, content-icon, event, room-type,
narrative-portrait, ending, challenge-reward, command-symbol and interface raster atlases generated by the script below
are original artwork drawn locally from deterministic pixel geometry.
No downloaded artwork, remote image generation, or third-party image is used.

The artwork is dedicated to the public domain under CC0 1.0 Universal:
https://creativecommons.org/publicdomain/zero/1.0/
The dedication applies to artwork only; it does not relicense game code,
project names, fonts, or third-party dependencies.

Source: tools/production_art/generate_ui_asset_slice.py
Reproduction: python3 tools/production_art/generate_ui_asset_slice.py
"""


def _rgba(value: tuple[int, int, int, int]) -> tuple[int, int, int, int]:
    return value


def _canvas() -> tuple[Image.Image, ImageDraw.ImageDraw]:
    image = Image.new("RGBA", (FRAME_SIZE, FRAME_SIZE), (0, 0, 0, 0))
    return image, ImageDraw.Draw(image)


def _frame_spark(draw: ImageDraw.ImageDraw, frame: int, color: tuple[int, int, int, int]) -> None:
    """Add a four-step charge/spark cue so every strip has meaningful frames."""
    for index in range(frame + 1):
        x = 27 - index * 3
        y = 5 + index * 2
        draw.rectangle((x, y, x + 1, y + 1), fill=color)
    draw.rectangle((4 + frame * 3, 27, 5 + frame * 3, 28), fill=color)


def _outline(draw: ImageDraw.ImageDraw, points: list[tuple[int, int]], fill: tuple[int, int, int, int]) -> None:
    draw.polygon(points, fill=PALETTE["ink"])
    inset = [(x + (1 if x < 16 else -1), y + (1 if y < 16 else -1)) for x, y in points]
    draw.polygon(inset, fill=fill)


def weapon_frame(weapon: str, frame: int) -> Image.Image:
    image, draw = _canvas()
    ink, stone, bone = PALETTE["ink"], PALETTE["stone"], PALETTE["bone"]
    patina, brass, ember = PALETTE["patina"], PALETTE["brass"], PALETTE["ember"]
    pulse = (0, 1, 0, -1)[frame]
    if weapon == "sword":
        _outline(draw, [(5, 25), (9, 21), (22, 8), (26, 10), (13, 24), (10, 28)], bone)
        draw.line([(8, 24), (23, 9)], fill=brass, width=2)
        draw.rectangle((4, 24, 12, 27), fill=patina)
        draw.rectangle((7, 27, 10, 30), fill=brass)
        draw.rectangle((12 + pulse, 6, 16 + pulse, 10), fill=PALETTE["time"])
        draw.line([(14, 20), (24, 10)], fill=PALETTE["muted"])
        draw.line([(6, 25), (10, 25)], fill=bone)
        draw.rectangle((8, 28, 9, 29), fill=PALETTE["brass_shadow"])
    elif weapon == "bow":
        draw.arc((5, 3, 25, 29), 72, 288, fill=ink, width=4)
        draw.arc((7, 5, 23, 27), 72, 288, fill=brass, width=2)
        draw.line([(10, 5), (10 + pulse, 27)], fill=bone, width=1)
        draw.line([(10, 16), (26, 16)], fill=patina, width=2)
        draw.polygon([(29, 16), (24, 13), (24, 19)], fill=PALETTE["time"])
        draw.rectangle((7, 14, 10, 18), fill=ember)
        draw.arc((8, 6, 22, 26), 85, 270, fill=PALETTE["brass_shadow"])
        draw.line([(8, 9), (10, 8)], fill=bone)
        draw.line([(8, 23), (10, 24)], fill=bone)
        draw.line([(12, 15), (23, 15)], fill=bone)
    elif weapon == "gun":
        draw.rectangle((5, 9, 24, 19), fill=ink)
        draw.rectangle((7, 11, 23, 17), fill=stone)
        draw.rectangle((20, 12, 29, 15), fill=bone)
        draw.rectangle((10, 18, 16, 26), fill=ink)
        draw.rectangle((12, 19, 15, 24), fill=patina)
        draw.rectangle((7, 12 + pulse, 10, 14 + pulse), fill=brass)
        draw.rectangle((27, 12, 30, 14), fill=ember)
        draw.line([(9, 11), (22, 11)], fill=PALETTE["edge"])
        draw.rectangle((16, 13, 19, 16), fill=brass)
        draw.line([(13, 20), (13, 23)], fill=PALETTE["time_shadow"])
        draw.line([(17, 19), (20, 19), (20, 22), (17, 22)], fill=brass)
    elif weapon == "staff":
        draw.line([(8, 28), (16, 7)], fill=ink, width=5)
        draw.line([(8, 28), (16, 7)], fill=brass, width=2)
        draw.ellipse((10, 3 + pulse, 22, 15 + pulse), fill=ink)
        draw.ellipse((12, 5 + pulse, 20, 13 + pulse), fill=PALETTE["time"])
        draw.rectangle((14, 8 + pulse, 17, 11 + pulse), fill=bone)
        draw.line([(17, 5 + pulse), (19, 7 + pulse)], fill=bone)
        draw.line([(10, 22), (12, 22)], fill=patina, width=2)
        draw.line([(11, 18), (13, 18)], fill=PALETTE["brass_shadow"], width=2)
    else:
        draw.rectangle((7, 11, 14, 23), fill=ink)
        draw.rectangle((18, 9, 25, 21), fill=ink)
        draw.rectangle((9, 12, 13, 20), fill=patina)
        draw.rectangle((19, 11, 23, 18), fill=brass)
        draw.line([(13, 17), (19, 15)], fill=bone, width=2)
        draw.rectangle((5, 8 + pulse, 10, 12 + pulse), fill=PALETTE["time"])
        draw.rectangle((22, 19 - pulse, 27, 23 - pulse), fill=ember)
        for x, y in ((9, 14), (9, 18), (19, 13), (19, 17)):
            draw.rectangle((x, y, x + 3, y + 1), fill=bone)
        draw.line([(12, 13), (12, 20)], fill=PALETTE["time_shadow"])
        draw.line([(22, 12), (22, 17)], fill=PALETTE["brass_shadow"])
    _frame_spark(draw, frame, PALETTE["time"])
    return image


def ability_frame(ability: str, frame: int) -> Image.Image:
    image, draw = _canvas()
    ink, stone, bone = PALETTE["ink"], PALETTE["stone"], PALETTE["bone"]
    time, brass, void = PALETTE["time"], PALETTE["brass"], PALETTE["void"]
    pulse = (0, 1, 0, -1)[frame]
    draw.rectangle((3, 3, 28, 28), fill=ink)
    draw.rectangle((5, 5, 26, 26), fill=stone)
    if ability == "stop":
        draw.ellipse((8, 8, 23, 23), outline=time, width=2)
        draw.rectangle((12, 11, 14, 20), fill=bone)
        draw.rectangle((18, 11, 20, 20), fill=bone)
        draw.rectangle((5, 14 + pulse, 8, 17 + pulse), fill=brass)
    elif ability == "rewind":
        draw.arc((8, 8, 24, 24), 35, 330, fill=time, width=3)
        draw.polygon([(7, 10), (14, 10), (10, 16)], fill=brass)
        draw.rectangle((14, 14, 18, 18), fill=bone)
        draw.rectangle((18, 18, 21, 21), fill=void)
    elif ability == "accelerate":
        draw.polygon([(7, 18), (15, 8), (14, 15), (24, 14), (15, 25), (16, 18)], fill=time)
        draw.line([(7, 24), (11, 20)], fill=bone, width=1)
        draw.line([(22, 9), (25, 6)], fill=brass, width=2)
    else:
        draw.polygon([(8, 8), (24, 8), (20, 14), (24, 23), (8, 23), (12, 16)], fill=void)
        draw.line([(8, 16), (24, 16)], fill=time, width=2)
        draw.rectangle((13, 13 + pulse, 18, 18 + pulse), fill=bone)
        draw.rectangle((5, 6, 9, 9), fill=brass)
    _frame_spark(draw, frame, PALETTE["brass"])
    return image


def effect_frame(effect: str, frame: int) -> Image.Image:
    image, draw = _canvas()
    ink, bone = PALETTE["ink"], PALETTE["bone"]
    patina, time, brass = PALETTE["patina"], PALETTE["time"], PALETTE["brass"]
    dim = PALETTE["time_shadow"]
    if effect == "weapon_arc":
        start, end = ((220, 252), (190, 282), (135, 310), (100, 345))[frame]
        draw.arc((3, 3, 29, 29), start, end, fill=ink, width=5)
        draw.arc((4, 4, 28, 28), start, end, fill=PALETTE["brass_shadow"], width=4)
        draw.arc((4, 4, 28, 28), start + 8, end, fill=brass, width=2)
        draw.arc((5, 5, 27, 27), end - 18, end, fill=bone, width=2)
    elif effect == "arrow_trail":
        tail = 2 + frame * 2
        draw.polygon([(tail, 16), (19, 13), (29, 16), (19, 19)], fill=ink)
        draw.line([(tail + 2, 16), (25, 16)], fill=dim, width=3)
        draw.line([(10 + frame, 16), (28, 16)], fill=time)
        draw.polygon([(29, 16), (24, 13), (25, 16), (24, 19)], fill=bone)
        draw.line([(3 + frame, 12), (8 + frame, 12)], fill=patina)
        draw.line([(5 + frame, 21), (9 + frame, 21)], fill=dim)
    elif effect == "muzzle_flash":
        reach = (17, 28, 25, 18)[frame]
        spread = (4, 10, 7, 3)[frame]
        draw.polygon([(3, 16), (11, 16 - spread), (13, 12), (reach, 16), (13, 20), (11, 16 + spread)], fill=ink)
        draw.polygon([(5, 16), (11, 18 - spread), (13, 14), (reach - 2, 16), (13, 18), (11, 14 + spread)], fill=brass)
        draw.polygon([(5, 16), (11, 14), (17 + (frame == 1) * 4, 16), (11, 18)], fill=bone)
        draw.rectangle((23 - frame, 8 + frame, 25 - frame, 9 + frame), fill=PALETTE["ember"])
        draw.rectangle((22, 23 - frame, 24, 24 - frame), fill=brass)
    elif effect == "spell_burst":
        radius = (4, 8, 11, 13)[frame]
        bounds = (16 - radius, 16 - radius, 16 + radius, 16 + radius)
        draw.ellipse(bounds, outline=ink, width=3)
        draw.arc(bounds, 20 + frame * 20, 140 + frame * 20, fill=time, width=2)
        draw.arc(bounds, 190 + frame * 15, 310 + frame * 15, fill=dim, width=2)
        core = (3, 4, 2, 1)[frame]
        draw.ellipse((16 - core, 16 - core, 16 + core, 16 + core), fill=bone)
        for x, y in ((16 - radius, 8), (22, 16 + radius), (16 + radius, 10)):
            draw.rectangle((x, y, x + 1, y + 1), fill=patina)
    elif effect == "time_ring":
        draw.ellipse((3, 3, 28, 28), outline=ink, width=3)
        draw.arc((4, 4, 27, 27), 15 + frame * 40, 135 + frame * 40, fill=time, width=2)
        draw.arc((4, 4, 27, 27), 180 + frame * 40, 290 + frame * 40, fill=dim, width=2)
        for x, y in ((15, 5), (24, 15), (15, 24), (5, 15)):
            draw.rectangle((x, y, x + 1, y + 1), fill=brass)
        hand = ((16, 7), (24, 16), (16, 25), (7, 16))[frame]
        draw.line([(16, 16), hand], fill=bone, width=1)
        draw.rectangle((14, 14, 17, 17), fill=time)
    else:
        reach = (6, 10, 13, 9)[frame]
        draw.polygon([(16 - reach, 18), (12, 13), (18, 16 - reach), (20, 13), (16 + reach, 18), (20, 21), (14, 16 + reach), (12, 21)], fill=ink)
        draw.line([(16 - reach + 2, 18), (13, 14), (18, 18 - reach), (19, 15)], fill=PALETTE["void_shadow"], width=3)
        draw.line([(19, 19), (16 + reach - 2, 18), (19, 20), (14, 14 + reach)], fill=PALETTE["void"], width=2)
        draw.line([(14, 16), (18, 20)], fill=time, width=2)
        draw.rectangle((16 - frame, 16 - frame, 18, 18), fill=bone)
    return image


def projectile_frame(projectile: str, frame: int) -> Image.Image:
    image, draw = _canvas()
    ink, bone, time, brass = (PALETTE[key] for key in ("ink", "bone", "time", "brass"))
    if projectile == "arrow":
        draw.line([(5, 16), (28, 16)], fill=ink, width=3)
        draw.line([(7, 16), (26, 16)], fill=brass)
        draw.polygon([(29, 16), (23, 12), (24, 16), (23, 20)], fill=ink)
        draw.polygon([(28, 16), (24, 14), (25, 16), (24, 18)], fill=bone)
        draw.polygon([(5, 16), (2, 12), (8, 14), (10, 16), (8, 18), (2, 20)], fill=PALETTE["patina"])
        draw.line([(2 + frame, 10), (7 + frame, 10)], fill=PALETTE["time_shadow"])
        draw.point((8 - frame, 22), fill=time)
    elif projectile == "bullet":
        draw.polygon([(8, 12), (23, 12), (28, 16), (23, 20), (8, 20)], fill=ink)
        draw.rectangle((10, 14, 21, 18), fill=PALETTE["brass_shadow"])
        draw.line([(10, 14), (21, 14), (25, 16)], fill=bone, width=2)
        draw.line([(10, 18), (21, 18)], fill=brass)
        draw.line([(1 + frame * 2, 16), (7, 16)], fill=brass)
        draw.point((5 + frame, 10), fill=PALETTE["ember"])
    elif projectile == "staff_fire":
        draw.polygon([(3, 9), (12, 11), (8, 5), (22, 9), (29, 16), (23, 23), (8, 27), (11, 21), (2, 23), (8, 16)], fill=ink)
        draw.polygon([(7 + frame, 12), (16, 11), (12, 8), (22, 12), (27, 16), (21, 22), (12, 24), (14, 19), (8, 20), (13, 16)], fill=PALETTE["danger"])
        draw.ellipse((15, 12, 24, 20), fill=brass)
        draw.line([(18, 14), (22, 16), (18, 18)], fill=bone, width=2)
    elif projectile == "staff_ice":
        draw.polygon([(6, 16), (15, 6), (27, 16), (15, 26)], fill=ink)
        draw.polygon([(8, 16), (15, 9), (24, 16), (15, 23)], fill=PALETTE["time_shadow"])
        draw.polygon([(15, 10), (24, 16), (15, 16)], fill=bone)
        draw.polygon([(9, 16), (15, 16), (15, 22)], fill=time)
        for x, y in ((3 + frame, 8), (7 - frame, 24)):
            draw.line([(x - 2, y), (x + 2, y)], fill=time)
            draw.line([(x, y - 2), (x, y + 2)], fill=time)
    elif projectile == "staff_lightning":
        shift = (0, 1, 0, -1)[frame]
        points = [(2, 13 + shift), (10, 10), (13, 17), (21, 12), (29, 16)]
        draw.line(points, fill=ink, width=6)
        draw.line(points, fill=brass, width=3)
        draw.line(points, fill=bone)
        draw.line([(11, 11), (8, 4 + frame), (16, 8)], fill=time)
        draw.line([(17, 16), (13 + frame, 26)], fill=brass)
    else:
        radius = (7, 8, 7, 6)[frame]
        draw.ellipse((16 - radius, 16 - radius, 16 + radius, 16 + radius), fill=ink, outline=PALETTE["void_shadow"], width=2)
        draw.arc((16 - radius + 1, 16 - radius + 1, 16 + radius - 1, 16 + radius - 1), 190, 340, fill=time, width=2)
        draw.ellipse((13, 13, 20, 20), fill=PALETTE["void"])
        draw.line([(15, 14), (18, 14), (20, 16)], fill=bone, width=2)
        draw.line([(3 + frame, 12), (8 + frame, 12)], fill=PALETTE["void_shadow"])
        draw.point((5 + frame, 22), fill=time)
    return image


def _content_colors(category: str) -> tuple[tuple[int, int, int, int], tuple[int, int, int, int], tuple[int, int, int, int]]:
    if category == "items":
        return PALETTE["patina"], PALETTE["time"], PALETTE["bone"]
    if category == "blessings":
        return PALETTE["brass"], PALETTE["bone"], PALETTE["patina"]
    if category == "curses":
        return PALETTE["danger"], PALETTE["ember"], PALETTE["void"]
    if category == "talents":
        return PALETTE["void"], PALETTE["time"], PALETTE["bone"]
    if category == "mode_art":
        return PALETTE["brass"], PALETTE["time"], PALETTE["bone"]
    return PALETTE["stone"], PALETTE["patina"], PALETTE["bone"]


_TOKEN_FAMILIES = (
    (("clock", "tempo", "chronal", "time", "stasis", "accelerat", "rewind"), 0),
    (("lens", "prism", "mirror", "focus", "draw"), 1),
    (("blade", "sword", "cleav", "edge", "gauntlet"), 2),
    (("anchor", "aegis", "guard", "fortress", "shield"), 3),
    (("rift", "void", "abyss", "fold", "corridor", "snare"), 4),
    (("echo", "history", "memory", "reservoir", "yesterday"), 5),
    (("core", "heart", "battery", "reserve", "energy"), 6),
    (("blood", "hunger", "siphon", "devour", "price"), 7),
    (("crown", "dominion", "throne", "legion", "sovereign"), 8),
    (("arrow", "ballistic", "rail", "shot", "pierc", "barrage"), 9),
    (("fire", "ember", "burn", "overdrive", "redline", "flame"), 10),
    (("bloom", "flower", "spore", "bramble", "root", "garden"), 11),
)


def glyph_family(category: str, asset_id: str) -> int:
    overrides = {"frozen_burst": 0, "frozen_afterimage": 5, "absolute_zero_device": 0,
                 "accelerated_combo": 2, "accelerant_window": 0, "redline_injector": 10,
                 "void_contract": 4, "void_brink": 4, "paradox_beacon": 0,
                 "focused_draw": 9, "piercing_draw": 9, "mirror_seed": 1,
                 "rewind_salve": 7, "brittle_vitality": 7, "narrow_escape": 3,
                 "risk_step": 4, "codex_margin": 5, "efficient_inscription": 5,
                 "boss_rush": 8, "daily_boss": 0, "authored_challenges": 2,
                 "training": 1, "endless": 4}
    if asset_id in overrides:
        return overrides[asset_id]
    lowered = asset_id.lower()
    matches = []
    for tokens, family in _TOKEN_FAMILIES:
        for token in tokens:
            if token in lowered:
                matches.append((lowered.rfind(token), len(token), family))
    if matches:
        return max(matches)[2]
    kind = CONTENT_METADATA.get(category, {}).get(asset_id, {}).get("kind", "")
    return {"survival": 3, "healing": 7, "weapon": 2, "time": 0,
            "time_skill": 0, "economy": 6, "positioning": 4, "risk": 7,
            "eternity": 0, "ruin": 2, "steel": 3, "time_guardian": 3,
            "void_walker": 4, "primordial_knight": 2, "time_lord": 5}.get(kind, 6)


@lru_cache(maxsize=None)
def _content_variant(category: str, asset_id: str) -> int:
    identities = CONTENT_METADATA.get(category, {}) if category != "mode_art" else MODE_ART
    related = sorted(identity for identity in identities if glyph_family(category, identity) == glyph_family(category, asset_id))
    return related.index(asset_id)


def content_frame(category: str, asset_id: str, frame: int) -> Image.Image:
    """Draw semantic artifact families with distinct housings, proportions and trim."""
    image, draw = _canvas()
    primary, accent, highlight = _content_colors(category)
    shape = glyph_family(category, asset_id)
    variant = _content_variant(category, asset_id)
    form, fit, trim = variant % 3, (variant // 3) % 3, variant // 9
    wobble = (0, 1, 0, -1)[frame]
    ink, stone, muted = PALETTE["ink"], PALETTE["stone"], PALETTE["muted"]
    cx, cy = 16, 16 + wobble
    radius = 8 + fit
    if category in ("blessings", "talents"):
        draw.arc((3, 3, 28, 28), 30, 150, fill=PALETTE["brass"], width=1)
        draw.arc((3, 3, 28, 28), 210, 330, fill=PALETTE["edge"], width=1)
    if shape == 0:
        if form == 0:
            draw.ellipse((cx - radius - 1, cy - radius - 1, cx + radius + 1, cy + radius + 1), fill=ink)
            draw.ellipse((cx - radius, cy - radius, cx + radius, cy + radius), fill=primary)
            draw.ellipse((cx - radius + 2, cy - radius + 2, cx + radius - 2, cy + radius - 2), fill=stone)
        elif form == 1:
            draw.polygon([(7 - fit, 5), (25 + fit, 5), (21, 12), (19, cy), (22, 23), (25 + fit, 27), (7 - fit, 27), (11, 22), (13, cy), (11, 11)], fill=ink)
            draw.line([(9 - fit, 6), (23 + fit, 6)], fill=primary, width=2)
            draw.line([(9 - fit, 26), (23 + fit, 26)], fill=primary, width=2)
            draw.polygon([(11, 9), (21, 9), (16, 16), (12, 23), (20, 23)], fill=accent)
        else:
            draw.polygon([(16, 3), (24 + fit, 10), (25, 22), (16, 28), (7, 22), (8 - fit, 10)], fill=ink)
            draw.polygon([(16, 5), (22 + fit, 11), (22, 21), (16, 25), (10, 21), (10 - fit, 11)], fill=primary)
            draw.polygon([(16, 6), (21, 12), (16, 15)], fill=highlight)
        if form != 1:
            draw.line([(16, cy), (16 + fit * 2, cy - 5)], fill=highlight, width=1)
            draw.line([(16, cy), (20 - trim, cy + 2)], fill=accent, width=2)
            for x, y in ((16, cy - 6), (22, cy), (16, cy + 6), (10, cy)):
                draw.point((x, y), fill=muted)
        draw.rectangle((13, 2 + trim, 19, 4 + trim), fill=primary)
    elif shape == 1:
        if form == 0:
            draw.ellipse((6 - fit, 5, 25, 24 + fit), fill=ink)
            draw.ellipse((8 - fit, 7, 23, 22 + fit), fill=primary)
            draw.ellipse((10 - fit, 9, 21, 20 + fit), fill=stone)
            draw.ellipse((13 - fit, 9, 20, 14), fill=accent)
            draw.line([(11, 22), (6, 28 - trim)], fill=primary, width=3)
        else:
            vertices = [(16, 4 + fit), (25, 12), (23, 23), (16, 27 - fit), (7, 23), (7, 12)] if form == 1 else [(7, 5), (24, 7 + fit), (26, 24), (6, 25 - fit)]
            draw.polygon(vertices, fill=ink)
            draw.polygon([(16, 7 + fit), (22, 13), (20, 22), (16, 24 - fit), (10, 21), (10, 13)], fill=accent)
            draw.line([(16, 8), (16, 23 - fit)], fill=primary, width=2)
        draw.line([(17, 10), (20, 13)], fill=highlight, width=2)
        draw.rectangle((18, 16 + trim, 20, 18 + trim), fill=primary)
    elif shape == 2:
        tip_x = 24 - fit
        draw.polygon([(7, 28), (4, 25), (9, 20), (tip_x - 3, 5 + form), (27, 4), (26 - form, 11 + fit), (13, 24)], fill=ink)
        draw.polygon([(10, 21), (tip_x - 2, 7 + form), (25, 6), (23 - form, 12 + fit), (12, 23)], fill=primary)
        draw.line([(11, 20), (24, 7 + form)], fill=highlight)
        draw.line([(7, 18), (16, 26)], fill=accent, width=2)
        draw.line([(6, 25), (10, 21)], fill=muted, width=2)
        if form == 1:
            draw.line([(15, 18), (20, 18), (18, 22)], fill=accent)
        elif form == 2:
            draw.polygon([(18, 10), (12, 8), (14, 16)], fill=accent)
        draw.rectangle((8 + trim, 25, 10 + trim, 27), fill=highlight)
    elif shape == 3:
        draw.polygon([(5 + fit, 5), (16, 3 + form), (27 - fit, 5), (25 - form, 19), (16, 28), (7 + form, 19)], fill=ink)
        draw.polygon([(7 + fit, 7), (16, 5 + form), (25 - fit, 7), (23 - form, 18), (16, 25), (9 + form, 18)], fill=primary)
        draw.polygon([(16, 6 + form), (23 - fit, 8), (21 - form, 17), (16, 23)], fill=highlight)
        draw.line([(16, 9 + trim), (16, 22 - trim)], fill=stone, width=2)
        draw.line([(10 + fit, 14), (22 - fit, 14)], fill=accent, width=2)
    elif shape == 4:
        draw.polygon([(7 - fit, 4), (19, 5 + form), (14, 12), (25 + fit, 15), (18, 21), (23, 28), (7, 25), (12, 19), (5, 13), (12, 9)], fill=ink)
        draw.line([(8 - fit, 5), (17, 6 + form), (12, 13), (23 + fit, 16), (15, 22), (21, 26)], fill=primary, width=3)
        draw.line([(13, 9), (11, 13), (22, 16), (16, 19)], fill=accent)
        draw.line([(6, 25 - trim), (10, 23 - trim)], fill=highlight, width=2)
        draw.rectangle((19 - form, 9 + fit, 22 - form, 11 + fit), fill=highlight)
    elif shape == 5:
        if form == 0:
            for offset, color in ((-5, PALETTE["edge"]), (0, primary), (5, accent)):
                draw.polygon([(13 + offset, 9 + fit), (17 + offset, 7 + fit), (19 + offset, 11 + fit), (18 + offset, 16), (21 + offset, 24), (10 + offset, 24), (13 + offset, 16)], fill=ink)
                draw.rectangle((14 + offset, 10 + fit, 17 + offset, 15), fill=color)
                draw.polygon([(14 + offset, 17), (17 + offset, 17), (19 + offset, 22), (12 + offset, 22)], fill=color)
        else:
            draw.polygon([(6, 6 + fit), (16, 8), (26, 6 + fit), (26 - form, 24), (16, 26), (6 + form, 24)], fill=ink)
            draw.polygon([(8, 8 + fit), (15, 10), (15, 23), (8 + form, 22)], fill=primary)
            draw.polygon([(17, 10), (24, 8 + fit), (24 - form, 22), (17, 23)], fill=highlight)
            for y in (13, 17, 20):
                draw.line([(18, y), (22 - trim, y)], fill=accent)
        draw.arc((3, 3, 28, 28), 190, 260 + trim * 12, fill=accent)
    elif shape == 6:
        draw.rectangle((8 - fit, 6, 24 + fit, 25), fill=ink)
        draw.rectangle((10 - fit, 8, 22 + fit, 23), fill=primary)
        draw.rectangle((12 - fit, 9, 20 + fit, 22), fill=stone)
        draw.rectangle((13, 3 + form, 19, 5 + form), fill=primary)
        draw.line([(23 + fit, 10), (23 + fit, 20)], fill=highlight)
        if form == 0:
            for y in range(11 + trim, 22, 4):
                draw.rectangle((14 - fit, y, 19 + fit, y + 1), fill=accent)
        elif form == 1:
            draw.polygon([(17, 9), (12, 17), (16, 16), (14, 22), (21, 14), (17, 15)], fill=accent)
        else:
            draw.ellipse((12 - fit, 11, 20 + fit, 20), fill=accent)
            draw.line([(17, 12), (19, 15)], fill=highlight)
    elif shape == 7:
        if form == 0:
            draw.polygon([(16, 3 + fit), (23 + fit, 15), (24, 21), (20, 27), (12, 27), (8, 21), (9 - fit, 15)], fill=ink)
            draw.polygon([(16, 6 + fit), (21 + fit, 16), (22, 21), (19, 25), (13, 25), (10, 21), (11 - fit, 16)], fill=primary)
        elif form == 1:
            draw.polygon([(5, 12), (8, 7 + fit), (13, 7 + fit), (16, 11), (19, 7 + fit), (24, 7 + fit), (27, 12), (25, 18), (16, 27), (7, 18)], fill=ink)
            draw.polygon([(7, 12), (10, 9 + fit), (13, 9 + fit), (16, 13), (19, 9 + fit), (23, 9 + fit), (25, 12), (23, 17), (16, 24), (9, 17)], fill=primary)
        else:
            draw.rectangle((9 - fit, 11, 23 + fit, 25), fill=ink)
            draw.rectangle((11 - fit, 12, 21 + fit, 23), fill=primary)
            draw.rectangle((12, 6, 20, 12), fill=stone)
            draw.rectangle((11, 4 + fit, 21, 7 + fit), fill=accent)
        draw.line([(18, 14 + wobble), (21, 17 + wobble), (20, 20 + wobble)], fill=highlight, width=2)
        draw.line([(11 + trim, 21), (15 + trim, 24)], fill=accent)
    elif shape == 8:
        draw.polygon([(4 + fit, 7), (11, 13 - form), (16, 4 + form), (21, 13 - form), (28 - fit, 7), (25, 25), (7, 25)], fill=ink)
        draw.polygon([(7 + fit, 10), (12, 16 - form), (16, 7 + form), (20, 16 - form), (25 - fit, 10), (23, 22), (9, 22)], fill=primary)
        draw.line([(10, 22), (23, 22)], fill=highlight, width=2)
        draw.polygon([(16, 16 - trim), (19, 18), (16, 21 + trim), (13, 18)], fill=accent)
        draw.line([(20, 13), (22, 16), (23, 14)], fill=highlight)
    elif shape == 9:
        draw.line([(5, 26 - fit), (23, 8 + form)], fill=ink, width=5)
        draw.line([(6, 25 - fit), (24, 7 + form)], fill=primary, width=2)
        draw.polygon([(27, 4 + form), (25, 15 + form), (20, 10 + form), (16, 8 + form)], fill=ink)
        draw.polygon([(25, 6 + form), (24, 12 + form), (20, 9 + form)], fill=highlight)
        draw.line([(5, 19 - fit), (12, 20 - fit), (12, 27 - fit)], fill=accent, width=2)
        if form > 0:
            draw.line([(7, 13 + trim), (17, 5 + trim)], fill=accent)
            draw.line([(16, 27 - fit), (26, 18 - fit)], fill=muted)
    elif shape == 10:
        draw.polygon([(8, 27), (4 + fit, 20), (10, 9 + form), (11, 17), (18, 3 + fit), (21, 13), (27 - form, 8), (25, 22), (22, 27)], fill=ink)
        draw.polygon([(9, 25), (7 + fit, 19), (11, 13 + form), (12, 20), (18, 7 + fit), (20, 17), (25 - form, 12), (23, 22), (20, 25)], fill=primary)
        draw.polygon([(13, 24), (12, 20), (18, 14 + trim), (18, 20), (21, 19), (20, 25)], fill=accent)
        draw.line([(16, 22), (17, 19)], fill=highlight, width=2)
    else:
        draw.line([(16, 26), (16, 13)], fill=ink, width=4)
        draw.line([(16, 25), (16, 14)], fill=primary, width=2)
        petals = [(10 - fit, 10, 16, 16), (16, 10, 22 + fit, 16), (13, 5 + form, 19, 13), (13, 14, 19, 21 - form)]
        for petal in petals:
            draw.ellipse(petal, fill=ink)
            draw.ellipse((petal[0] + 1, petal[1] + 1, petal[2] - 1, petal[3] - 1), fill=accent)
        draw.ellipse((13, 11 + wobble, 19, 17 + wobble), fill=highlight)
        draw.polygon([(15, 23), (7, 19 - trim), (10, 25)], fill=primary)
        draw.polygon([(17, 23), (25, 18 + trim), (22, 25)], fill=primary)
    if category == "curses":
        draw.line([(20, 5), (17, 11), (20, 14), (14, 22)], fill=ink, width=2)
        draw.line([(19, 6), (16, 11), (19, 14), (13, 23)], fill=accent)
    _frame_spark(draw, frame, highlight)
    return image


def ui_frame(asset_id: str, frame: int) -> Image.Image:
    image, draw = _canvas()
    ink, stone, edge = PALETTE["ink"], PALETTE["stone"], PALETTE["edge"]
    time, brass = PALETTE["time"], PALETTE["brass"]
    if asset_id.startswith("chrome_"):
        focus = asset_id == "chrome_focus"
        border = PALETTE["patina"] if focus else edge
        draw.rectangle((1, 1, 30, 30), fill=None if focus else ink, outline=border)
        if not focus:
            draw.rectangle((2, 2, 29, 29), outline=stone)
            draw.line([(4, 2), (27, 2)], fill=edge)
            draw.line([(4, 29), (27, 29)], fill=stone)
        for x, y in ((1, 1), (28, 1), (1, 28), (28, 28)):
            draw.rectangle((x, y, x + 2, y + 2), fill=border)
            draw.point((x + 1, y + 1), fill=brass if frame % 2 == 0 else border)
        draw.line([(7 + frame * 4, 1), (9 + frame * 4, 1)], fill=time if focus else brass)
        return image
    if asset_id == "divider":
        draw.rectangle((4, 14, 27, 17), fill=ink)
        draw.rectangle((6, 15, 25, 16), fill=time)
        draw.rectangle((8 + frame, 12, 10 + frame, 19), fill=brass)
    elif asset_id == "badge":
        draw.polygon([(7, 7), (25, 7), (23, 24), (16, 28), (9, 24)], fill=ink)
        draw.polygon([(9, 9), (23, 9), (21, 22), (16, 25), (11, 22)], fill=brass)
        draw.rectangle((14, 13, 18, 19), fill=time)
    elif asset_id == "cursor":
        draw.polygon([(8, 5), (8, 27), (14, 21), (19, 27), (22, 24), (17, 18), (25, 18)], fill=ink)
        draw.polygon([(10, 8), (10, 22), (14, 18), (19, 24), (20, 23), (15, 17), (22, 17)], fill=time)
    else:
        draw.rectangle((4, 4, 27, 27), fill=ink)
        draw.rectangle((6, 6, 25, 25), fill=stone)
        border = time if asset_id == "panel_active" else PALETTE["danger"] if asset_id == "panel_danger" else edge
        draw.rectangle((7, 7, 24, 24), outline=border, width=2)
        draw.rectangle((10, 10, 21, 11), fill=brass if frame % 2 == 0 else border)
    _frame_spark(draw, frame, brass)
    return image


def room_type_frame(room_type: str, frame: int) -> Image.Image:
    image, draw = _canvas()
    ink, stone, edge, bone = (PALETTE[key] for key in ("ink", "stone", "edge", "bone"))
    time, brass, patina, danger = (PALETTE[key] for key in ("time", "brass", "patina", "danger"))
    if room_type == "entry":
        draw.rectangle((5, 7, 26, 28), fill=ink)
        draw.rectangle((7, 8, 10, 26), fill=edge)
        draw.rectangle((22, 8, 24, 26), fill=edge)
        draw.polygon([(7, 8), (11, 3), (21, 3), (25, 8)], fill=stone)
        draw.line([(12, 4), (21, 4), (23, 7)], fill=bone)
        draw.rectangle((12, 9, 20, 24), fill=PALETTE["time_shadow"])
        draw.line([(16, 11), (16, 22)], fill=time, width=2)
        draw.rectangle((5, 27, 26, 29), fill=brass)
    elif room_type == "unknown":
        draw.ellipse((5, 4, 26, 27), fill=ink, outline=edge)
        draw.line([(11, 11), (11, 8), (14, 7), (19, 7), (21, 10), (20, 13), (16, 16), (16, 19)], fill=bone, width=2)
        draw.rectangle((15, 23, 17, 25), fill=time)
    elif room_type == "combat":
        for mirrored, color in ((False, bone), (True, patina)):
            points = [(5, 3), (10, 6), (23, 22), (21, 24), (8, 10)]
            if mirrored:
                points = [(31 - x, y) for x, y in points]
            draw.polygon(points, fill=ink)
            draw.line([(25 if mirrored else 6, 6), (9 if mirrored else 22, 22)], fill=color, width=2)
            draw.line([(7 if mirrored else 19, 20), (14 if mirrored else 26, 26)], fill=brass, width=2)
    elif room_type == "elite":
        draw.polygon([(8, 11), (12, 7), (21, 7), (25, 11), (24, 24), (16, 28), (8, 24)], fill=ink)
        draw.polygon([(10, 11), (13, 9), (21, 9), (23, 12), (22, 23), (16, 25), (10, 23)], fill=brass)
        draw.rectangle((11, 14, 22, 18), fill=stone)
        draw.line([(12, 16), (21, 16)], fill=danger)
        draw.line([(17, 9), (17, 25)], fill=bone)
        draw.polygon([(13, 5), (16, 2), (19, 5), (16, 7)], fill=danger)
    elif room_type == "treasure":
        draw.rectangle((4, 10, 27, 27), fill=ink)
        draw.rectangle((6, 12, 25, 25), fill=PALETTE["brass_shadow"])
        draw.polygon([(6, 11), (9, 6), (22, 6), (25, 11)], fill=brass)
        draw.line([(9, 7), (22, 7), (24, 11)], fill=bone)
        draw.rectangle((5, 16, 26, 18), fill=ink)
        for x in (8, 21):
            draw.line([(x, 12), (x, 24)], fill=brass, width=2)
        draw.rectangle((14, 15, 18, 21), fill=brass)
        draw.rectangle((16, 17, 17, 19), fill=ink)
    elif room_type == "shop":
        draw.rectangle((7, 10, 25, 27), fill=ink)
        draw.rectangle((10, 15, 22, 25), fill=stone)
        draw.polygon([(4, 14), (9, 5), (23, 5), (28, 14)], fill=ink)
        draw.polygon([(7, 12), (11, 7), (14, 7), (12, 12)], fill=patina)
        draw.polygon([(14, 12), (16, 7), (20, 7), (21, 12)], fill=bone)
        draw.rectangle((9, 21, 24, 26), fill=PALETTE["brass_shadow"])
        draw.ellipse((17, 16, 23, 22), fill=brass, outline=bone)
    elif room_type == "event":
        draw.rectangle((9, 5, 23, 27), fill=ink)
        draw.rectangle((11, 7, 21, 25), fill=bone)
        draw.rectangle((6, 5, 23, 8), fill=brass)
        draw.rectangle((8, 24, 26, 27), fill=brass)
        draw.line([(13, 11), (19, 11)], fill=edge)
        draw.line([(13, 14), (19, 14)], fill=edge)
        draw.ellipse((14, 17, 21, 23), fill=danger, outline=PALETTE["danger_shadow"])
        draw.point((18, 18), fill=bone)
    elif room_type == "boss":
        draw.polygon([(10, 11), (3, 4), (6, 17), (10, 20), (13, 28), (20, 28), (24, 20), (27, 17), (29, 4), (22, 11)], fill=ink)
        draw.polygon([(8, 11), (4, 6), (8, 17), (10, 17)], fill=brass)
        draw.polygon([(23, 11), (27, 6), (24, 17), (21, 17)], fill=brass)
        draw.ellipse((9, 9, 23, 24), fill=bone)
        draw.rectangle((12, 21, 20, 25), fill=bone)
        draw.polygon([(11, 14), (15, 16), (14, 19), (11, 18)], fill=danger)
        draw.polygon([(22, 14), (17, 16), (18, 19), (21, 18)], fill=danger)
        draw.rectangle((15, 20, 17, 22), fill=ink)
        draw.line([(14, 24), (14, 26)], fill=ink)
        draw.line([(18, 24), (18, 26)], fill=ink)
    elif room_type == "rest":
        draw.line([(6, 26), (25, 22)], fill=ink, width=5)
        draw.line([(6, 23), (25, 27)], fill=ink, width=5)
        draw.line([(7, 26), (24, 23)], fill=PALETTE["brass_shadow"], width=2)
        draw.line([(7, 24), (24, 26)], fill=brass, width=2)
        draw.polygon([(10, 23), (7, 17), (13, 7), (14, 15), (19, 3), (22, 15), (26, 12), (23, 22)], fill=danger)
        draw.polygon([(12, 22), (12, 17), (18, 10), (18, 18), (22, 15), (21, 22)], fill=brass)
        draw.line([(16, 20), (17, 16)], fill=bone, width=2)
    else:
        raise ValueError("Unknown room-type art: " + room_type)
    if room_type != "unknown":
        draw.rectangle((26 - frame * 2, 2, 27 - frame * 2, 3), fill=time)
    else:
        draw.point((25, 8 + frame * 4), fill=edge)
    return image


def control_frame(control: str, frame: int) -> Image.Image:
    image, draw = _canvas()
    bone, ink, time = PALETTE["bone"], PALETTE["ink"], PALETTE["time"]
    if control == "play":
        draw.polygon([(9, 5), (27, 16), (9, 27)], fill=ink)
        draw.polygon([(12, 9), (23, 16), (12, 23)], fill=bone)
    elif control == "pause":
        for x in (7, 19):
            draw.rectangle((x, 5, x + 6, 27), fill=ink)
            draw.rectangle((x + 2, 8, x + 4, 24), fill=bone)
    elif control in ("copy", "paste"):
        draw.rectangle((6, 4, 21, 23), fill=ink)
        draw.rectangle((8, 6, 19, 21), outline=PALETTE["edge"], width=2)
        draw.rectangle((12, 10, 27, 29), fill=ink)
        draw.rectangle((14, 12, 25, 27), outline=bone, width=2)
        if control == "paste":
            draw.rectangle((15, 8, 24, 13), fill=time)
            draw.line([(17, 19), (23, 19)], fill=bone)
            draw.line([(17, 23), (21, 23)], fill=bone)
    elif control == "export":
        draw.line([(5, 21), (5, 27), (27, 27), (27, 21)], fill=ink, width=5)
        draw.line([(5, 21), (5, 27), (27, 27), (27, 21)], fill=bone, width=2)
        draw.line([(16, 23), (16, 5)], fill=ink, width=6)
        draw.line([(16, 22), (16, 6)], fill=time, width=2)
        draw.line([(9, 12), (16, 5), (23, 12)], fill=time, width=3)
    elif control == "delete":
        draw.rectangle((9, 9, 24, 27), fill=ink)
        draw.rectangle((11, 11, 22, 25), outline=bone, width=2)
        draw.line([(6, 7), (27, 7)], fill=bone, width=2)
        draw.line([(13, 4), (20, 4)], fill=bone, width=2)
        for x in (15, 19):
            draw.line([(x, 14), (x, 22)], fill=PALETTE["danger"])
    elif control == "back":
        draw.line([(27, 16), (5, 16)], fill=ink, width=6)
        draw.line([(15, 6), (5, 16), (15, 26)], fill=ink, width=6)
        draw.line([(26, 16), (7, 16)], fill=bone, width=2)
        draw.line([(15, 8), (7, 16), (15, 24)], fill=bone, width=2)
    elif control == "settings":
        for x, y in ((13, 3), (13, 25), (3, 13), (25, 13), (6, 6), (23, 6), (6, 23), (23, 23)):
            draw.rectangle((x, y, x + 4, y + 4), fill=PALETTE["edge"])
        draw.ellipse((6, 6, 26, 26), fill=ink, outline=bone, width=3)
        draw.ellipse((12, 12, 20, 20), fill=ink, outline=time, width=2)
    elif control == "bindings":
        draw.rectangle((3, 7, 28, 25), fill=ink, outline=bone)
        for y in (11, 16):
            for x in (7, 13, 19, 24):
                draw.rectangle((x, y, x + 2, y + 2), fill=bone)
        draw.rectangle((10, 21, 21, 22), fill=time)
    elif control == "restart":
        draw.arc((5, 5, 27, 27), 40, 325, fill=ink, width=6)
        draw.arc((5, 5, 27, 27), 40, 325, fill=bone, width=2)
        draw.polygon([(24, 4), (24, 14), (15, 10)], fill=time)
    elif control == "quit":
        draw.rectangle((5, 4, 20, 28), fill=ink, outline=bone, width=2)
        draw.polygon([(7, 6), (16, 9), (16, 24), (7, 26)], fill=PALETTE["stone"])
        draw.line([(13, 16), (28, 16)], fill=time, width=2)
        draw.line([(22, 10), (28, 16), (22, 22)], fill=time, width=2)
    elif control == "build":
        draw.rectangle((5, 4, 26, 28), fill=ink, outline=bone)
        draw.line([(10, 8), (23, 8)], fill=PALETTE["edge"])
        for x, y in ((9, 12), (20, 12), (9, 22), (20, 22)):
            draw.rectangle((x - 2, y - 2, x + 2, y + 2), outline=time if x < 16 else PALETTE["brass"])
        draw.line([(12, 13), (18, 13), (18, 21), (12, 21)], fill=PALETTE["edge"])
    elif control == "import":
        draw.line([(5, 21), (5, 27), (27, 27), (27, 21)], fill=ink, width=5)
        draw.line([(5, 21), (5, 27), (27, 27), (27, 21)], fill=bone, width=2)
        draw.line([(16, 4), (16, 22)], fill=time, width=2)
        draw.line([(9, 15), (16, 22), (23, 15)], fill=time, width=3)
    elif control == "refresh":
        draw.arc((5, 5, 27, 27), 185, 340, fill=bone, width=2)
        draw.arc((5, 5, 27, 27), 5, 160, fill=bone, width=2)
        draw.polygon([(27, 6), (27, 15), (19, 11)], fill=time)
        draw.polygon([(5, 26), (5, 17), (13, 21)], fill=PALETTE["patina"])
    elif control == "next":
        draw.line([(5, 16), (25, 16)], fill=ink, width=6)
        draw.line([(16, 7), (25, 16), (16, 25)], fill=ink, width=6)
        draw.line([(6, 16), (24, 16)], fill=bone, width=2)
        draw.line([(16, 8), (24, 16), (16, 24)], fill=bone, width=2)
        draw.line([(28, 7), (28, 25)], fill=time, width=2)
    elif control == "screenshot":
        draw.rectangle((3, 10, 29, 26), fill=ink, outline=bone, width=2)
        draw.rectangle((8, 6, 17, 10), fill=bone)
        draw.ellipse((11, 13, 22, 24), fill=ink, outline=time, width=2)
        draw.rectangle((25, 13, 26, 14), fill=PALETTE["brass"])
    elif control == "account":
        draw.ellipse((10, 4, 23, 17), fill=ink, outline=bone, width=2)
        draw.polygon([(4, 29), (6, 22), (12, 19), (21, 19), (27, 23), (29, 29)], fill=ink, outline=bone)
        draw.line([(8, 27), (25, 27)], fill=time)
    elif control == "storage":
        draw.rectangle((5, 4, 27, 29), fill=ink, outline=bone, width=2)
        draw.rectangle((9, 5, 21, 13), fill=PALETTE["edge"])
        draw.rectangle((17, 7, 19, 11), fill=ink)
        draw.rectangle((10, 18, 23, 26), outline=time)
        draw.line([(13, 21), (21, 21)], fill=bone)
    elif control == "community":
        for x, y, color in ((9, 10, bone), (23, 10, bone), (16, 18, time)):
            draw.ellipse((x - 3, y - 4, x + 3, y + 2), fill=ink, outline=color)
            draw.line([(x - 5, y + 9), (x - 3, y + 4), (x + 3, y + 4), (x + 5, y + 9)], fill=color, width=2)
    elif control == "content":
        draw.polygon([(4, 11), (16, 5), (28, 11), (28, 24), (16, 30), (4, 24)], fill=ink, outline=bone)
        draw.line([(5, 11), (16, 17), (27, 11)], fill=bone)
        draw.line([(16, 17), (16, 28)], fill=time, width=2)
        draw.line([(10, 8), (21, 14), (21, 19)], fill=PALETTE["brass"], width=2)
    elif control == "sharing":
        draw.line([(8, 16), (24, 7)], fill=bone, width=2)
        draw.line([(8, 16), (24, 25)], fill=bone, width=2)
        for x, y in ((8, 16), (24, 7), (24, 25)):
            draw.ellipse((x - 4, y - 4, x + 4, y + 4), fill=ink, outline=time, width=2)
    else:
        draw.rectangle((7, 5, 23, 27), fill=ink)
        draw.rectangle((9, 7, 21, 25), fill=PALETTE["muted"])
        for y in (11, 15, 19):
            draw.line([(12, y), (18, y)], fill=PALETTE["stone"])
        draw.line([(4, 25), (26, 5)], fill=ink, width=5)
        draw.line([(5, 24), (25, 6)], fill=PALETTE["danger"], width=2)
    draw.rectangle((27 - frame * 2, 1, 28 - frame * 2, 2), fill=time)
    return image


def portrait_frame(npc: str, frame: int) -> Image.Image:
    image = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    ink, stone, edge, bone, muted = (PALETTE[key] for key in ("ink", "stone", "edge", "bone", "muted"))
    brass, patina, time, void = (PALETTE[key] for key in ("brass", "patina", "time", "void"))
    bronze, cool, dusk = (PALETTE[key] for key in ("brass_shadow", "time_shadow", "void_shadow"))
    cloth, shadow = {
        "odysseus": (brass, bronze), "elara": (patina, cool), "sibyl": (void, dusk),
        "hermes": (PALETTE["ember"], bronze), "phia": (patina, edge), "morpheus": (edge, stone),
        "nemesis": (PALETTE["danger"], PALETTE["danger_shadow"]), "vera": (time, cool),
    }[npc]
    draw.polygon([(7, 60), (9, 46), (22, 39), (44, 39), (57, 49), (60, 61)], fill=ink)
    draw.polygon([(10, 59), (12, 48), (24, 41), (43, 41), (54, 50), (57, 59)], fill=shadow)
    draw.polygon([(12, 48), (24, 42), (29, 51), (23, 59), (10, 59)], fill=cloth)
    draw.polygon([(35, 51), (43, 42), (50, 47), (54, 59), (40, 59)], fill=cloth)
    draw.line([(13, 47), (24, 42), (28, 49)], fill=bone)
    draw.line([(46, 48), (50, 58)], fill=shadow, width=2)
    draw.rectangle((27, 34, 38, 46), fill=ink)
    draw.rectangle((29, 35, 36, 44), fill=bronze)
    draw.polygon([(28, 41), (33, 45), (37, 41), (39, 47), (33, 51), (25, 46)], fill=bone)

    jaw = {"odysseus": (24, 39), "elara": (25, 36), "sibyl": (27, 36), "hermes": (26, 38), "phia": (22, 37), "morpheus": (23, 40), "nemesis": (26, 37), "vera": (27, 35)}[npc]
    face = [(21, 15), (27, 10), (37, 10), (44, 17), (44, 29), (39, jaw[1]), (32, jaw[1] + 2), (jaw[0], jaw[1] - 1), (20, 29)]
    draw.polygon(face, fill=ink)
    draw.polygon([(23, 16), (28, 12), (37, 12), (42, 18), (42, 29), (37, 36), (31, 38), (25, 34), (22, 28)], fill=muted)
    draw.polygon([(24, 17), (29, 13), (35, 13), (37, 17), (36, 27), (32, 29), (26, 28), (23, 23)], fill=bone)
    draw.rectangle((19, 23, 21, 28), fill=muted)
    draw.rectangle((43, 24, 45, 28), fill=bronze)
    draw.line([(34, 22), (34, 28), (38, 29)], fill=bronze)
    draw.line([(29, 34), (35, 34)], fill=bronze)
    for left, right in ((25, 29), (36, 40)):
        draw.line([(left, 21), (right, 21)], fill=ink)
        draw.line([(left, 25), (right - 1, 25)], fill=ink)
        if frame == 2:
            draw.line([(left, 26), (right - 1, 26)], fill=muted)
        else:
            draw.rectangle((left + 1, 24, left + 2, 25), fill=cool)
            draw.point((left + 1, 24), fill=time if npc in ("sibyl", "vera") else bone)

    if npc == "odysseus":
        draw.polygon([(19, 22), (18, 12), (24, 5), (38, 5), (45, 12), (45, 22), (40, 16), (27, 13), (23, 20)], fill=ink)
        draw.polygon([(21, 16), (23, 9), (30, 7), (39, 8), (43, 13), (40, 14), (27, 12)], fill=muted)
        draw.line([(24, 9), (30, 8), (38, 9)], fill=bone, width=2)
        draw.line([(24, 20), (29, 20)], fill=edge, width=2)
        draw.line([(36, 20), (41, 22)], fill=edge, width=2)
        draw.line([(23, 28), (26, 29)], fill=bronze)
        draw.line([(40, 28), (42, 27)], fill=bronze)
        draw.polygon([(23, 30), (27, 32), (32, 35), (38, 31), (41, 29), (40, 38), (34, 43), (27, 40)], fill=edge)
        draw.line([(26, 34), (29, 39), (33, 41)], fill=bone)
        draw.line([(37, 34), (35, 39)], fill=muted)
        draw.rectangle((29, 51, 38, 58), fill=brass, outline=ink)
        draw.line([(32, 53), (35, 53), (34, 56)], fill=bone)
        draw.line([(19, 45), (24, 52), (21, 59)], fill=bronze, width=2)
    elif npc == "elara":
        draw.polygon([(16, 50), (17, 20), (21, 8), (33, 5), (44, 11), (48, 29), (46, 50), (40, 48), (41, 20), (32, 12), (23, 19), (23, 44)], fill=ink)
        draw.polygon([(18, 45), (19, 19), (24, 9), (33, 7), (39, 10), (27, 17), (23, 31), (22, 45)], fill=bronze)
        draw.line([(22, 14), (27, 10), (33, 9)], fill=brass, width=2)
        draw.line([(45, 20), (45, 42)], fill=PALETTE["ember"], width=2)
        for y in (27, 32, 37, 42):
            draw.polygon([(43, y), (47, y + 1), (45, y + 5), (42, y + 3)], fill=brass, outline=bronze)
        draw.rectangle((42, 45, 46, 47), fill=patina)
        draw.line([(27, 33), (31, 34), (35, 33)], fill=bronze)
        draw.line([(25, 20), (29, 20)], fill=bronze)
        draw.polygon([(31, 49), (36, 48), (39, 53), (34, 58), (30, 54)], fill=ink)
        draw.polygon([(32, 50), (35, 50), (37, 53), (34, 56), (32, 54)], fill=time)
        draw.point((33 + frame % 2, 52), fill=bone)
    elif npc == "sibyl":
        draw.polygon([(13, 45), (14, 23), (22, 8), (31, 3), (42, 9), (49, 26), (50, 48), (41, 45), (43, 24), (33, 12), (22, 23), (23, 44)], fill=ink)
        draw.line([(15, 42), (17, 24), (24, 10), (31, 6), (41, 12)], fill=void, width=2)
        draw.line([(46, 26), (47, 43)], fill=dusk, width=3)
        draw.line([(23, 18), (31, 10), (38, 16)], fill=brass)
        draw.rectangle((30, 15, 34, 18), fill=dusk)
        draw.rectangle((32, 14, 33, 16), fill=time)
        draw.polygon([(25, 39), (31, 43), (39, 39), (40, 45), (33, 48), (26, 45)], fill=dusk)
        draw.line([(14, 52), (21, 55), (27, 52)], fill=void)
        draw.line([(25, 21), (29, 22)], fill=dusk)
        draw.line([(36, 22), (40, 21)], fill=dusk)
        draw.line([(21, 40), (18, 48), (21, 58)], fill=dusk, width=2)
    elif npc == "hermes":
        draw.polygon([(13, 19), (17, 11), (21, 11), (23, 5), (40, 7), (43, 13), (51, 18), (46, 21), (21, 20)], fill=ink)
        draw.polygon([(17, 17), (22, 13), (25, 7), (38, 9), (41, 15), (46, 18)], fill=cloth)
        draw.line([(22, 15), (41, 17)], fill=brass, width=2)
        draw.polygon([(36, 10), (42, 2), (47, 3), (43, 10)], fill=bone)
        draw.line([(42, 4), (38, 12)], fill=patina)
        draw.line([(21, 48), (43, 58)], fill=ink, width=5)
        draw.line([(21, 48), (43, 58)], fill=brass, width=2)
        draw.ellipse((10, 50, 24, 62), fill=bronze, outline=ink, width=2)
        draw.rectangle((15, 52, 20, 54), fill=brass)
        draw.line([(29, 33), (33, 35), (38, 32)], fill=ink)
        draw.line([(35, 23), (35, 27), (40, 28), (38, 30)], fill=bronze)
        draw.line([(24, 21), (28, 20)], fill=bronze)
        draw.line([(36, 20), (40, 20)], fill=bronze)
        draw.rectangle((24, 29, 26, 30), fill=PALETTE["ember"])
    elif npc == "phia":
        draw.polygon([(17, 29), (17, 12), (24, 6), (37, 5), (45, 12), (47, 27), (42, 30), (40, 17), (29, 14), (22, 21)], fill=ink)
        draw.polygon([(20, 19), (21, 12), (25, 8), (35, 7), (41, 13), (34, 14), (28, 12)], fill=edge)
        draw.line([(23, 11), (29, 9), (35, 9)], fill=patina, width=2)
        draw.line([(25, 29), (29, 30)], fill=cool)
        draw.line([(38, 30), (40, 28)], fill=cool)
        draw.polygon([(22, 29), (27, 30), (28, 34), (24, 34)], fill=edge)
        draw.line([(23, 30), (26, 31)], fill=patina)
        draw.polygon([(38, 31), (42, 29), (41, 35), (38, 36)], fill=edge)
        draw.line([(40, 31), (40, 33)], fill=bone)
        draw.line([(25, 20), (29, 22)], fill=edge, width=2)
        for points in ([(9, 45), (15, 41), (23, 45), (19, 53), (9, 54)], [(43, 45), (51, 44), (57, 51), (51, 56), (44, 53)]):
            draw.polygon(points, fill=edge, outline=ink)
            draw.line(points[:3], fill=bone)
        draw.rectangle((28, 50, 39, 61), fill=edge, outline=ink)
        draw.line([(30, 52), (35, 52), (33, 56), (37, 58)], fill=patina)
    elif npc == "morpheus":
        draw.polygon([(20, 22), (18, 13), (23, 6), (34, 5), (45, 12), (45, 21), (40, 17), (27, 14), (24, 21)], fill=ink)
        draw.polygon([(21, 14), (25, 8), (33, 7), (41, 12), (39, 15), (29, 12)], fill=edge)
        draw.line([(24, 10), (30, 8)], fill=bone, width=2)
        draw.line([(23, 21), (29, 22)], fill=edge, width=2)
        draw.line([(36, 21), (41, 20)], fill=edge, width=2)
        draw.line([(24, 31), (28, 33)], fill=bronze)
        draw.line([(40, 32), (37, 35)], fill=bronze)
        draw.polygon([(27, 35), (31, 37), (38, 34), (38, 39), (32, 41), (27, 39)], fill=edge)
        draw.line([(30, 37), (34, 38)], fill=muted)
        draw.line([(38, 18), (35, 24), (37, 31)], fill=PALETTE["danger_shadow"])
        draw.line([(22, 26), (26, 29)], fill=bronze)
        draw.rectangle((9, 46, 24, 54), fill=ink)
        draw.rectangle((10, 47, 22, 51), fill=muted)
        draw.line([(13, 48), (19, 48)], fill=bone)
        draw.polygon([(29, 47), (36, 44), (44, 48), (40, 60), (29, 60)], fill=stone)
        draw.line([(36, 46), (34, 57)], fill=brass)
        draw.line([(32, 56), (39, 56)], fill=brass, width=2)
    elif npc == "nemesis":
        draw.polygon([(16, 22), (17, 11), (25, 4), (38, 4), (45, 12), (48, 25), (42, 31), (40, 17), (32, 11), (22, 21)], fill=ink)
        draw.line([(19, 17), (25, 7), (38, 7), (44, 17)], fill=dusk, width=3)
        draw.polygon([(31, 2), (37, 9), (33, 17), (28, 9)], fill=brass, outline=ink)
        draw.line([(32, 5), (33, 10)], fill=bone)
        draw.polygon([(8, 45), (16, 41), (26, 46), (23, 54), (8, 53)], fill=stone, outline=ink)
        draw.line([(10, 46), (16, 44), (23, 47)], fill=muted, width=2)
        draw.line([(31, 48), (35, 56)], fill=brass, width=2)
        draw.line([(37, 48), (29, 56)], fill=brass, width=2)
        draw.rectangle((24, 18, 29, 19), fill=PALETTE["danger_shadow"])
        draw.line([(24, 21), (29, 23)], fill=ink, width=2)
        draw.line([(36, 23), (41, 21)], fill=ink, width=2)
        draw.line([(36, 30), (36, 33)], fill=PALETTE["danger_shadow"])
        draw.line([(11, 55), (22, 58)], fill=dusk, width=2)
    elif npc == "vera":
        draw.polygon([(17, 47), (18, 17), (23, 7), (34, 4), (44, 10), (48, 30), (45, 47), (41, 45), (41, 19), (33, 12), (24, 20), (23, 43)], fill=ink)
        draw.line([(20, 41), (20, 18), (25, 9), (34, 7), (42, 12)], fill=muted, width=3)
        draw.line([(23, 16), (28, 10), (35, 8)], fill=bone)
        draw.line([(44, 22), (45, 36)], fill=cool, width=2)
        draw.line([(38, 18), (35, 25), (39, 31), (34, 37)], fill=time)
        draw.polygon([(29, 48), (36, 48), (39, 53), (35, 59), (29, 56)], fill=ink)
        draw.line([(31, 50), (35, 50), (37, 53), (34, 57)], fill=time, width=2)
        draw.rectangle((48, 52 + frame, 51, 55 + frame), fill=time)
        draw.rectangle((43, 58 - frame, 45, 60 - frame), fill=cool)
        draw.rectangle((50, 56, 54, 59), fill=(0, 0, 0, 0))
        draw.rectangle((13, 58, 16, 61), fill=(0, 0, 0, 0))
        draw.line([(26, 21), (29, 21)], fill=cool)
        draw.line([(36, 21), (39, 22)], fill=cool)
    else:
        raise ValueError("Unknown narrative portrait: " + npc)
    # A local material glint gives static accessibility consumers a stable first frame.
    draw.line([(12 + frame * 2, 57), (14 + frame * 2, 57)], fill=bone)
    return image


def reward_frame(reward: str, frame: int) -> Image.Image:
    image, draw = _canvas()
    ink, stone, edge, bone, time, brass, patina, void = (PALETTE[key] for key in ("ink", "stone", "edge", "bone", "time", "brass", "patina", "void"))
    bronze, cool, dusk = (PALETTE[key] for key in ("brass_shadow", "time_shadow", "void_shadow"))
    if reward == "walker_proof":
        draw.polygon([(7, 3), (25, 3), (24, 22), (16, 29), (8, 22)], fill=ink)
        draw.polygon([(9, 5), (23, 5), (22, 21), (16, 26), (10, 21)], fill=bronze)
        draw.line([(10, 6), (21, 6), (20, 20), (16, 23)], fill=brass, width=2)
        draw.polygon([(16, 8), (21, 16), (16, 21), (11, 16)], fill=ink)
        draw.line([(13, 16), (16, 11), (19, 16), (16, 19)], fill=bone, width=2)
    elif reward == "speedwalker_boots":
        for x, y in ((6, 4), (16, 8)):
            draw.polygon([(x, y), (x + 8, y), (x + 7, y + 11), (x + 11, y + 15), (x + 11, y + 19), (x - 2, y + 19), (x - 2, y + 14)], fill=ink)
            draw.polygon([(x + 2, y + 2), (x + 6, y + 2), (x + 5, y + 12), (x + 9, y + 16), (x, y + 16)], fill=patina)
            draw.line([(x, y + 18), (x + 9, y + 18)], fill=bone)
            draw.line([(x + 2, y + 5), (x + 5, y + 5)], fill=brass)
            draw.line([(x + 2, y + 3), (x + 2, y + 10)], fill=bone)
            draw.line([(x + 1, y + 14), (x + 5, y + 14)], fill=cool, width=2)
            draw.line([(x + 3, y + 16), (x + 8, y + 16)], fill=brass)
        draw.line([(2, 24), (8, 24)], fill=time)
        draw.line([(2, 28), (5, 28)], fill=cool)
    elif reward in ("walker_entry", "eternal_walker", "void_walker", "daily_character_color"):
        color, shadow = {"walker_entry": (time, cool), "eternal_walker": (brass, bronze), "void_walker": (void, dusk), "daily_character_color": (patina, cool)}[reward]
        draw.polygon([(10, 13), (10, 6), (15, 2), (22, 7), (22, 13), (25, 19), (28, 27), (22, 29), (9, 29), (3, 27), (7, 18)], fill=ink)
        draw.polygon([(12, 12), (12, 7), (15, 4), (20, 8), (20, 12), (16, 14)], fill=shadow)
        draw.rectangle((14, 9, 18, 11), fill=bone)
        draw.polygon([(10, 16), (15, 19), (21, 16), (25, 26), (8, 26)], fill=shadow)
        draw.line([(11, 16), (15, 18), (20, 16)], fill=color, width=2)
        draw.line([(10, 20), (9, 25), (21, 25)], fill=color, width=2)
        draw.line([(18, 20), (20, 24)], fill=ink)
        draw.rectangle((14, 23, 18, 24), fill=brass if reward != "eternal_walker" else bone)
        if reward == "walker_entry":
            draw.line([(26, 5), (28, 7), (26, 9)], fill=time)
        elif reward == "eternal_walker":
            draw.arc((3, 1, 29, 27), 205, 330, fill=brass)
            draw.polygon([(16, 14), (19, 18), (16, 22), (13, 18)], fill=bone)
        elif reward == "void_walker":
            draw.polygon([(24, 7), (28, 11), (25, 15), (27, 20)], fill=dusk)
            draw.line([(25, 8), (27, 11), (25, 14)], fill=void)
        else:
            draw.rectangle((3, 3, 6, 6), fill=patina)
            draw.rectangle((3, 8, 6, 11), fill=brass)
    elif reward in ("daily_participation_frame", "daily_walker_frame"):
        color = patina if reward == "daily_participation_frame" else brass
        draw.rectangle((4, 4, 28, 28), fill=ink, outline=color, width=2)
        draw.rectangle((8, 8, 24, 24), outline=edge)
        for x, y in ((3, 3), (25, 3), (3, 25), (25, 25)):
            draw.rectangle((x, y, x + 4, y + 4), fill=color)
            draw.point((x + 1, y + 1), fill=bone)
        if reward == "daily_participation_frame":
            draw.line([(11, 17), (15, 21), (22, 12)], fill=patina, width=2)
        else:
            draw.polygon([(11, 15), (16, 10), (21, 15), (19, 19), (13, 19)], fill=brass)
            draw.line([(14, 20), (12, 24)], fill=bone)
            draw.line([(18, 20), (20, 24)], fill=bone)
    elif reward == "eternal_traveler":
        draw.polygon([(3, 10), (10, 12), (10, 24), (3, 25), (5, 18)], fill=ink, outline=brass)
        draw.polygon([(28, 10), (21, 12), (21, 24), (28, 25), (26, 18)], fill=ink, outline=brass)
        draw.rectangle((8, 12, 23, 22), fill=bronze, outline=ink)
        draw.line([(9, 20), (22, 20)], fill=brass)
        draw.line([(10, 14), (21, 14)], fill=brass)
        draw.line([(11, 17), (20, 17)], fill=bone, width=2)
        draw.polygon([(16, 3), (20, 7), (16, 11), (12, 7)], fill=time, outline=ink)
    elif reward == "daily_weapon_skin":
        draw.polygon([(4, 26), (9, 21), (23, 6), (28, 3), (27, 10), (12, 25), (9, 29)], fill=ink)
        draw.line([(9, 24), (26, 6)], fill=PALETTE["danger"], width=3)
        draw.line([(11, 21), (25, 6)], fill=bone)
        draw.line([(5, 20), (13, 28)], fill=brass, width=2)
        draw.line([(4, 29), (7, 26)], fill=bronze, width=3)
        draw.polygon([(22, 23), (26, 19), (30, 23), (26, 27)], fill=PALETTE["danger"], outline=ink)
    elif reward == "daily_archive_decoration":
        draw.rectangle((6, 25, 26, 29), fill=ink)
        draw.rectangle((8, 26, 24, 28), fill=bronze)
        draw.rectangle((10, 19, 22, 25), fill=stone, outline=edge)
        draw.polygon([(16, 3), (23, 8), (21, 16), (16, 20), (9, 15), (10, 7)], fill=ink)
        draw.polygon([(16, 5), (21, 9), (19, 15), (16, 18), (11, 14), (12, 8)], fill=time)
        draw.line([(16, 6), (14, 11), (16, 16)], fill=bone, width=2)
        draw.line([(12, 23), (20, 23)], fill=brass)
        draw.line([(10, 27), (23, 27)], fill=bone)
    else:
        raise ValueError("Unknown challenge reward: " + reward)
    _frame_spark(draw, frame, time)
    return image


def ending_frame(ending: str, frame: int) -> Image.Image:
    image = Image.new("RGBA", (128, 72), PALETTE["ink"])
    draw = ImageDraw.Draw(image)
    ink, stone, edge, bone = (PALETTE[key] for key in ("ink", "stone", "edge", "bone"))
    brass, time, void, patina = (PALETTE[key] for key in ("brass", "time", "void", "patina"))
    bronze, cool, dusk = (PALETTE[key] for key in ("brass_shadow", "time_shadow", "void_shadow"))
    muted = PALETTE["muted"]
    draw.polygon([(0, 38), (10, 30), (16, 34), (25, 19), (37, 31), (47, 25), (63, 35), (79, 19), (90, 27), (99, 13), (112, 24), (127, 17), (127, 55), (0, 55)], fill=stone)
    draw.polygon([(0, 58), (24, 45), (48, 51), (63, 44), (86, 50), (105, 43), (127, 57), (127, 71), (0, 71)], fill=edge)
    draw.polygon([(0, 63), (24, 51), (49, 57), (63, 50), (86, 56), (105, 49), (127, 63), (127, 71), (0, 71)], fill=stone)
    for x, y in ((5, 53), (16, 59), (107, 57), (116, 51)):
        draw.line([(x, y), (x + 6, y - 2)], fill=muted)

    def figure(x, y, color, walking=False):
        draw.rectangle((x - 2, y - 15, x + 2, y - 11), fill=ink)
        draw.rectangle((x - 1, y - 14, x + 1, y - 12), fill=bone)
        draw.polygon([(x - 3, y - 10), (x + 3, y - 10), (x + 5, y - 2), (x - 5, y - 2)], fill=ink)
        draw.line([(x - 2, y - 9), (x - 3, y - 3), (x + 3, y - 3)], fill=color, width=2)
        draw.line([(x - 2, y - 2), (x - 3 if walking else x - 2, y + 1)], fill=bone)
        draw.line([(x + 2, y - 2), (x + 4 if walking else x + 2, y + 1)], fill=muted)

    def shard(x, y, color, scale=1):
        points = [(x, y - 4 * scale), (x + 3 * scale, y - scale), (x + scale, y + 4 * scale), (x - 3 * scale, y + 2 * scale), (x - 2 * scale, y - 2 * scale)]
        draw.polygon(points, fill=color, outline=ink)
        draw.line([(x, y - 2 * scale), (x + scale, y)], fill=bone)

    if ending == "return_of_order":
        for x in (14, 99):
            draw.rectangle((x, 21, x + 13, 51), fill=ink)
            draw.rectangle((x + 2, 23, x + 10, 50), fill=stone)
            draw.line([(x + 2, 24), (x + 9, 24), (x + 9, 48)], fill=brass)
            draw.rectangle((x - 2, 19, x + 15, 23), fill=bronze)
        draw.line([(24, 58), (61, 40), (105, 57)], fill=ink, width=7)
        draw.line([(24, 58), (61, 40), (105, 57)], fill=brass, width=2)
        shard(62, 24, brass, 3)
        for x, y in ((43, 15), (77, 12), (85, 31), (40, 34)):
            shard(x, y + (frame % 2), time)
        draw.rectangle((52, 40, 76, 44), fill=ink, outline=brass)
        draw.rectangle((55, 44, 73, 49), fill=bronze)
        figure(40, 58, patina)
        figure(84, 58, brass)
        for x in (12, 22, 105, 115):
            draw.rectangle((x, 60, x + 3, 64), fill=ink, outline=muted)
    elif ending == "embrace_of_void":
        draw.polygon([(39, 47), (40, 18), (48, 7), (62, 3), (79, 11), (88, 25), (88, 48)], fill=ink)
        draw.line([(40, 46), (42, 20), (49, 10), (63, 6), (78, 13), (85, 25), (86, 47)], fill=dusk, width=3)
        draw.line([(45, 43), (45, 23), (51, 14), (63, 9), (75, 16)], fill=void)
        draw.polygon([(52, 40), (58, 20), (67, 12), (72, 28), (77, 41)], fill=stone)
        draw.line([(48, 48), (81, 48)], fill=void, width=2)
        figure(38, 57, void)
        figure(89, 59, PALETTE["danger"])
        draw.line([(91, 58), (104, 63)], fill=bone, width=2)
        draw.line([(89, 59), (102, 65)], fill=brass)
        draw.line([(62, 70), (61, 54), (64, 45)], fill=dusk, width=4)
        shard(64, 39 + frame % 2, muted)
    elif ending == "balance_of_ashes":
        draw.polygon([(6, 62), (43, 42), (62, 37), (70, 40), (34, 60), (18, 71)], fill=bronze)
        draw.polygon([(120, 63), (84, 42), (70, 38), (66, 44), (95, 63), (111, 71)], fill=dusk)
        draw.line([(14, 63), (48, 44), (62, 40)], fill=brass, width=2)
        draw.line([(114, 64), (82, 46), (72, 41)], fill=void, width=2)
        draw.rectangle((53, 44, 76, 48), fill=ink, outline=muted)
        for x, y, color in ((47, 25, brass), (65, 16, time), (83, 26, void)):
            shard(x, y + (frame % 2), color, 2)
        figure(30, 60, patina)
        figure(96, 61, void)
        figure(63, 54, bone)
        for x, y in ((12, 44), (20, 48), (106, 47), (114, 42)):
            draw.line([(x, y), (x + 3, y - 7)], fill=patina)
            draw.rectangle((x + 1, y - 6, x + 4, y - 4), fill=patina)
    elif ending == "shattered_freedom":
        draw.line([(63, 71), (64, 54), (31, 37)], fill=ink, width=7)
        draw.line([(64, 54), (99, 36)], fill=ink, width=7)
        draw.line([(63, 70), (64, 54), (31, 37)], fill=brass, width=2)
        draw.line([(64, 54), (99, 36)], fill=patina, width=2)
        figure(63, 62, bone, True)
        draw.line([(67, 52), (73, 47)], fill=bone, width=2)
        for x, y, color in ((24, 20, brass), (43, 13, time), (65, 5, bone), (86, 15, void), (105, 24, patina)):
            shard(x, y + (frame % 2), color, 2)
        for x in (15, 105):
            draw.rectangle((x, 31, x + 8, 43), fill=ink, outline=edge)
            draw.line([(x + 2, 34), (x + 6, 34)], fill=bone)
        figure(35, 48, patina, True)
        figure(93, 48, void, True)
    elif ending == "echo_of_primordial":
        draw.rectangle((41, 9, 87, 51), fill=ink)
        draw.rectangle((46, 12, 82, 49), fill=cool)
        draw.rectangle((48, 13, 80, 48), fill=stone)
        for x in (37, 84):
            draw.rectangle((x, 13, x + 6, 50), fill=edge, outline=ink)
            draw.line([(x + 1, 15), (x + 1, 46)], fill=bone)
        draw.polygon([(38, 14), (44, 5), (79, 5), (91, 14)], fill=ink)
        draw.line([(41, 12), (46, 8), (77, 8), (85, 12)], fill=brass, width=2)
        draw.rectangle((51, 17, 60, 46), fill=ink, outline=patina)
        draw.rectangle((69, 17, 77, 46), fill=ink, outline=void)
        draw.line([(62, 48), (63, 35), (65, 22)], fill=time, width=2)
        draw.polygon([(59, 20), (61, 15), (65, 16), (67, 13), (70, 20)], fill=patina)
        draw.rectangle((37, 51, 90, 55), fill=edge, outline=ink)
        draw.rectangle((32, 56, 95, 60), fill=edge, outline=ink)
        figure(64, 65, bone, True)
        for x, color in ((21, brass), (32, patina), (96, void), (109, time)):
            figure(x, 65, color)
        draw.line([(61, 32 + frame), (66, 32 + frame)], fill=bone)
    else:
        raise ValueError("Unknown ending artwork: " + ending)
    draw.rectangle((4 + frame * 3, 67, 6 + frame * 3, 68), fill=brass)
    return image


def event_frame(event: str, frame: int) -> Image.Image:
    image = Image.new("RGBA", (96, 64), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    ink, stone, edge, bone = (PALETTE[key] for key in ("ink", "stone", "edge", "bone"))
    brass, time, void, danger = (PALETTE[key] for key in ("brass", "time", "void", "danger"))
    draw.polygon([(8, 51), (24, 45), (70, 45), (88, 51), (70, 59), (23, 59)], fill=ink)
    draw.line([(14, 52), (26, 56), (68, 56), (81, 51)], fill=stone, width=2)

    def pedestal(x=31, y=38, width=35):
        draw.rectangle((x + 6, y + 3, x + width - 6, 52), fill=stone)
        draw.rectangle((x, y, x + width, y + 5), fill=ink)
        draw.line([(x + 2, y + 1), (x + width - 2, y + 1)], fill=edge)
        draw.rectangle((x + 6, 49, x + width - 6, 52), fill=edge)

    def clock(x=48, y=24, radius=13, color=time):
        draw.ellipse((x - radius, y - radius, x + radius, y + radius), fill=ink, outline=brass, width=2)
        draw.ellipse((x - radius + 4, y - radius + 4, x + radius - 4, y + radius - 4), outline=color)
        hand = ((x, y - 7), (x + 7, y), (x, y + 7), (x - 7, y))[frame]
        draw.line([(x, y), hand], fill=bone, width=2)

    def traveler(x, y, color):
        draw.ellipse((x - 6, y - 16, x + 6, y - 4), fill=ink, outline=color, width=2)
        draw.rectangle((x - 3, y - 10, x + 2, y - 6), fill=bone)
        draw.polygon([(x - 6, y - 3), (x + 5, y - 3), (x + 10, y + 12), (x - 11, y + 12)], fill=ink)
        draw.line([(x - 5, y), (x - 8, y + 10), (x + 8, y + 10)], fill=color, width=2)

    if event in ("event_chronal_altar", "event_perfect_rewind"):
        pedestal()
        clock()
        if event == "event_perfect_rewind":
            draw.arc((23, 2, 74, 48), 140, 330, fill=time, width=2)
            draw.polygon([(28, 11), (25, 20), (34, 19)], fill=bone)
            draw.rectangle((45, 44, 50, 49), fill=time)
        else:
            for x in (22, 73):
                draw.rectangle((x, 27, x + 3, 44), fill=brass)
                draw.rectangle((x - 1, 21 + frame, x + 4, 25 + frame), fill=time)
    elif event == "event_trapped_traveler":
        traveler(48, 36, time)
        for x, y in ((19, 32), (30, 23), (56, 28), (68, 36)):
            draw.polygon([(x, y), (x + 11, y - 5), (x + 17, y + 9), (x + 5, y + 15)], fill=ink)
            draw.line([(x + 2, y), (x + 10, y - 3), (x + 15, y + 7)], fill=edge, width=2)
    elif event == "event_cursed_pool":
        draw.ellipse((15, 29, 82, 54), fill=ink, outline=edge, width=3)
        draw.ellipse((21, 32, 76, 48), fill=PALETTE["void_shadow"], outline=void)
        for x in (31, 47, 64):
            draw.arc((x - 5, 30, x + 5, 44), 10, 150, fill=void)
            draw.line([(x, 28), (x - 2 + frame, 18), (x + 2, 13)], fill=void)
    elif event == "event_smiths_legacy":
        pedestal(27, 40, 43)
        draw.polygon([(22, 25), (74, 25), (65, 32), (57, 36), (59, 40), (37, 40), (39, 32), (28, 31)], fill=edge, outline=ink)
        draw.line([(48, 29), (62, 9)], fill=brass, width=4)
        draw.polygon([(53, 8), (59, 4), (73, 12), (68, 19)], fill=ink)
        draw.line([(55, 9), (67, 16)], fill=bone, width=4)
    elif event == "event_memory_mirror":
        pedestal(26, 48, 44)
        draw.ellipse((29, 4, 67, 47), fill=ink, outline=brass, width=3)
        draw.ellipse((34, 9, 62, 43), fill=PALETTE["time_shadow"], outline=time)
        traveler(49, 29, PALETTE["patina"])
        draw.line([(39, 13), (36, 26)], fill=bone, width=2)
    elif event == "event_planar_merchant":
        traveler(61, 33, brass)
        draw.rectangle((19, 33, 52, 51), fill=ink)
        draw.rectangle((21, 36, 50, 48), fill=PALETTE["brass_shadow"], outline=brass)
        draw.polygon([(20, 32), (22, 21), (53, 24), (51, 35)], fill=stone, outline=edge)
        for x, color in ((25, time), (34, void), (43, bone)):
            draw.rectangle((x, 36, x + 5, 43), fill=color)
    elif event in ("event_void_rift", "event_void_whispers"):
        draw.polygon([(45, 3), (63, 14), (58, 28), (70, 43), (48, 54), (30, 44), (35, 29), (26, 15)], fill=ink, outline=void)
        draw.line([(45, 6), (40, 19), (53, 27), (45, 40), (48, 50)], fill=PALETTE["void_shadow"], width=6)
        draw.line([(45, 9), (43, 21), (51, 28), (46, 40)], fill=time, width=2)
        if event == "event_void_whispers":
            draw.polygon([(36, 21), (45, 25), (39, 29)], fill=bone)
            draw.polygon([(62, 21), (51, 25), (59, 29)], fill=bone)
            for x in (19, 73):
                draw.line([(x, 43), (x + 3, 29), (x - 2, 22)], fill=void)
    elif event == "event_sleeping_guardian":
        draw.rectangle((22, 13, 73, 51), fill=stone, outline=edge, width=2)
        draw.rectangle((42, 26, 54, 51), fill=ink)
        traveler(48, 30, edge)
        draw.polygon([(27, 30), (35, 25), (39, 30), (38, 47), (33, 52), (27, 47)], fill=ink, outline=brass)
        draw.line([(62, 17), (62, 50)], fill=bone, width=2)
    elif event == "event_twisted_well":
        draw.rectangle((22, 37, 74, 52), fill=stone, outline=edge, width=2)
        draw.ellipse((21, 31, 74, 44), fill=ink, outline=bone, width=2)
        for x in (25, 69):
            draw.line([(x, 36), (x, 11)], fill=PALETTE["brass_shadow"], width=4)
        draw.line([(21, 11), (74, 11)], fill=brass, width=3)
        draw.line([(47, 11), (47, 35)], fill=bone)
        draw.rectangle((42, 26 + frame, 53, 35 + frame), fill=brass, outline=ink)
    elif event == "event_soul_contract":
        draw.polygon([(29, 8), (66, 12), (62, 48), (24, 43)], fill=bone, outline=brass, width=2)
        for y in (18, 23, 28):
            draw.line([(34, y), (57, y + 3)], fill=edge)
        draw.ellipse((42, 31, 54, 43), fill=danger, outline=PALETTE["danger_shadow"])
        draw.line([(48, 42), (43, 55)], fill=danger, width=3)
        draw.line([(49, 42), (53, 56)], fill=danger, width=3)
    elif event == "event_time_paradox":
        traveler(32, 37, time)
        traveler(64, 37, void)
        draw.arc((22, 5, 75, 46), 195, 340, fill=time, width=2)
        draw.arc((22, 9, 75, 50), 15, 155, fill=void, width=2)
        draw.rectangle((45, 26, 50, 31), fill=bone)
    elif event == "event_sacrificial_altar":
        pedestal(22, 28, 52)
        draw.rectangle((27, 20, 69, 30), fill=ink, outline=bone, width=2)
        draw.polygon([(47, 9), (40, 19), (40, 25), (47, 28), (54, 25), (54, 19)], fill=danger)
        draw.line([(46, 13), (43, 20)], fill=bone)
        draw.line([(48, 29), (48, 45)], fill=PALETTE["danger_shadow"], width=2)
    elif event == "event_lost_journal":
        draw.polygon([(17, 23), (44, 19), (49, 24), (73, 20), (77, 44), (49, 49), (22, 45)], fill=ink)
        draw.polygon([(20, 25), (43, 22), (48, 26), (71, 23), (74, 42), (49, 46), (24, 42)], fill=bone)
        draw.line([(47, 26), (49, 45)], fill=PALETTE["brass_shadow"], width=2)
        draw.line([(28, 30), (40, 28), (38, 36), (31, 39)], fill=PALETTE["time_shadow"])
        draw.line([(57, 29), (68, 27)], fill=edge)
        draw.line([(57, 34), (67, 32)], fill=edge)
        draw.rectangle((79, 25, 83, 43), fill=brass)
        draw.polygon([(79, 23), (81, 15 + frame), (84, 24)], fill=danger)
    elif event == "event_rift_garden":
        for x, y, color in ((28, 31, void), (48, 20, time), (66, 34, bone)):
            draw.line([(x, 51), (x, y)], fill=PALETTE["patina"], width=2)
            draw.line([(x, 43), (x - 7, 37)], fill=PALETTE["patina"], width=2)
            for dx, dy in ((-5, 0), (5, 0), (0, -5), (0, 5)):
                draw.ellipse((x + dx - 4, y + dy - 3, x + dx + 4, y + dy + 3), fill=color, outline=ink)
            draw.rectangle((x - 2, y - 2, x + 2, y + 2), fill=brass)
    elif event == "event_final_choice":
        draw.rectangle((27, 40, 69, 51), fill=stone, outline=edge)
        draw.polygon([(32, 16), (40, 22), (48, 10), (57, 22), (65, 16), (62, 34), (35, 34)], fill=ink, outline=brass, width=2)
        draw.rectangle((37, 32, 60, 36), fill=brass)
        draw.polygon([(48, 18), (44, 24), (48, 30), (52, 24)], fill=time)
    elif event == "event_old_reunion":
        traveler(31, 37, brass)
        traveler(66, 37, PALETTE["patina"])
        draw.line([(37, 38), (43, 33), (50, 33)], fill=bone, width=2)
        draw.line([(59, 38), (52, 33)], fill=bone, width=2)
        draw.polygon([(48, 20), (44, 27), (48, 34), (52, 27)], fill=time, outline=ink)
    else:
        raise ValueError("Unknown event artwork: " + event)
    draw.rectangle((18 + frame * 17, 4 + frame % 2 * 3, 20 + frame * 17, 6 + frame % 2 * 3), fill=time)
    return image


def _atlas(frames: Iterable[Image.Image]) -> Image.Image:
    frames = list(frames)
    width, height = frames[0].size
    if len(frames) != FRAME_COUNT or any(frame.size != (width, height) for frame in frames):
        raise ValueError("Atlas frames must have matching dimensions and declared count")
    atlas = Image.new("RGBA", (width * FRAME_COUNT, height), (0, 0, 0, 0))
    for index, frame in enumerate(frames):
        atlas.paste(frame, (index * width, 0))
    return atlas


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _write_atlases(destination: Path, family: str, ids: tuple[str, ...], renderer) -> list[dict]:
    family_dir = destination / family
    family_dir.mkdir(parents=True, exist_ok=True)
    rows: list[dict] = []
    for asset_id in ids:
        path = family_dir / f"{asset_id}.png"
        atlas = _atlas(renderer(asset_id, frame) for frame in range(FRAME_COUNT))
        atlas.save(path)
        rows.append({
            "id": asset_id,
            "path": str(path.relative_to(destination)),
            "kind": family,
            "width": atlas.width,
            "height": atlas.height,
            "frame_width": atlas.width // FRAME_COUNT,
            "frame_height": atlas.height,
            "frame_count": FRAME_COUNT,
            "filter": "nearest",
            "sha256": _sha(path),
        })
    return rows


def _existing_inventory(root: Path, family: str, ids: tuple[str, ...], manifest_name: str, path_key: str = "path") -> list[dict]:
    manifest_path = root / family / manifest_name
    if not manifest_path.exists():
        return []
    source = json.loads(manifest_path.read_text())
    source_rows = source.get("assets", source.get("atlases", []))
    output: list[dict] = []
    for row in source_rows:
        asset_id = str(row.get("id", Path(str(row.get(path_key, ""))).stem))
        if ids and asset_id not in ids:
            continue
        relative = str(row[path_key])
        file_path = root / family / relative
        if not file_path.exists():
            continue
        output.append({
            "id": asset_id,
            "path": str(file_path.relative_to(root)),
            "kind": family,
            "source_manifest": str(manifest_path.relative_to(root)),
            "filter": row.get("filter", "nearest"),
            "sha256": _sha(file_path),
        })
    return output


def _content_ids() -> dict[str, tuple[str, ...]]:
    result: dict[str, tuple[str, ...]] = {}
    for category, path in CONTENT_SOURCES.items():
        source = json.loads(path.read_text())
        result[category] = tuple(str(row["id"]) for row in source if isinstance(row, dict) and str(row.get("id", "")))
    return result


def _contact_sheet(destination: Path, generated: list[dict], existing: list[dict]) -> None:
    rows = generated + existing
    thumb_w, thumb_h = 128, 72
    columns = 4
    sheet = Image.new("RGBA", (columns * thumb_w, ((len(rows) + columns - 1) // columns) * (thumb_h + 18)), (17, 22, 25, 255))
    draw = ImageDraw.Draw(sheet)
    for index, row in enumerate(rows):
        x = (index % columns) * thumb_w
        y = (index // columns) * (thumb_h + 18)
        source = destination / row["path"] if "source_manifest" not in row else ROOT / "assets" / "production" / row["path"]
        image = Image.open(source).convert("RGBA")
        image.thumbnail((thumb_w - 8, thumb_h - 8), Image.Resampling.NEAREST)
        sheet.alpha_composite(image, (x + (thumb_w - image.width) // 2, y + 2))
        draw.text((x + 4, y + thumb_h), row["id"][:19], fill=PALETTE["bone"])
    sheet.save(destination / "pixel_asset_contact_sheet.png")


def _narrative_contact_sheet(destination: Path) -> None:
    sheet = Image.new("RGBA", (576, 568), PALETTE["ink"])
    draw = ImageDraw.Draw(sheet)
    for index, identity in enumerate(NPC_IDS):
        x, y = 8 + index % 4 * 144, 8 + index // 4 * 156
        sheet.alpha_composite(portrait_frame(identity, 0).resize((128, 128), Image.Resampling.NEAREST), (x, y))
        draw.text((x, y + 130), identity, fill=PALETTE["bone"])
    for index, identity in enumerate(ENDING_IDS):
        x, y = 8 + index % 3 * 188, 320 + index // 3 * 120
        sheet.alpha_composite(ending_frame(identity, 0), (x, y))
        draw.text((x, y + 76), identity, fill=PALETTE["bone"])
    sheet.save(destination / "narrative_contact_sheet.png")


def generate(destination: Path = OUTPUT) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    generated: list[dict] = []
    generated += _write_atlases(destination, "weapons", WEAPONS, weapon_frame)
    generated += _write_atlases(destination, "time_abilities", ABILITIES, ability_frame)
    generated += _write_atlases(destination, "player_effects", EFFECTS, effect_frame)
    generated += _write_atlases(destination, "player_projectiles", PROJECTILES, projectile_frame)
    generated += _write_atlases(destination, "room_types", ROOM_TYPES, room_type_frame)
    generated += _write_atlases(destination, "event_art", EVENT_IDS, event_frame)
    generated += _write_atlases(destination, "npc_portraits", NPC_IDS, portrait_frame)
    generated += _write_atlases(destination, "ending_art", ENDING_IDS, ending_frame)
    generated += _write_atlases(destination, "challenge_rewards", REWARD_IDS, reward_frame)
    generated += _write_atlases(destination, "controls", CONTROLS, control_frame)
    content_ids = _content_ids()
    for category, ids in content_ids.items():
        generated += _write_atlases(destination, category, ids, lambda asset_id, frame, family=category: content_frame(family, asset_id, frame))
    generated += _write_atlases(destination, "mode_art", MODE_ART, lambda asset_id, frame: content_frame("mode_art", asset_id, frame))
    generated += _write_atlases(destination, "final_ui_frames", UI_FRAMES, ui_frame)
    for row in generated:
        if row["kind"] in (*content_ids.keys(), "mode_art"):
            row["glyph_family"] = glyph_family(str(row["kind"]), str(row["id"]))

    production_root = ROOT / "assets" / "production"
    font_manifest = json.loads((production_root / "fonts/manifest.json").read_text())
    fonts = [{**row, "path": "../fonts/" + row["path"], "license_path": "../fonts/" + row["license_path"], "kind": "font"} for row in font_manifest["assets"]]
    existing: list[dict] = []
    existing += _existing_inventory(production_root, "actors", tuple(), "manifest.json")
    existing += _existing_inventory(production_root, "enemies", tuple(), "manifest.json")
    existing += _existing_inventory(production_root, "rooms", tuple(), "manifest.json", "path")
    _contact_sheet(destination, generated, existing)
    _narrative_contact_sheet(destination)

    inventory = {
        "schema_id": "plane_walker_pixel_asset_inventory_v1",
        "schema_version": 1,
        "generated_by": "tools/production_art/generate_ui_asset_slice.py",
        "nearest_filter": True,
        "palette": {key: "#%02x%02x%02x" % value[:3] for key, value in PALETTE.items()},
        "batches": [
            {"id": "actors", "status": "generated", "scope": "five players and five bosses", "assets": [row for row in existing if row["kind"] == "actors"]},
            {"id": "enemies", "status": "generated", "scope": "twenty-two launch enemy phase atlases", "assets": [row for row in existing if row["kind"] == "enemies"]},
            {"id": "rooms", "status": "generated", "scope": "room tiles, walls, doors and landmarks", "assets": [row for row in existing if row["kind"] == "rooms"]},
            {"id": "weapons", "status": "generated", "scope": "five weapon icons", "assets": [row for row in generated if row["kind"] == "weapons"]},
            {"id": "time_abilities", "status": "generated", "scope": "four time ability icons", "assets": [row for row in generated if row["kind"] == "time_abilities"]},
            {"id": "player_effects", "status": "generated", "scope": "weapon and time projectile/effect strips", "assets": [row for row in generated if row["kind"] == "player_effects"]},
            {"id": "player_projectiles", "status": "generated", "scope": "arrow, bullet and four staff element projectile strips", "assets": [row for row in generated if row["kind"] == "player_projectiles"]},
            {"id": "room_types", "status": "generated", "scope": "revealed room types and a distinct unknown glyph", "assets": [row for row in generated if row["kind"] == "room_types"]},
            {"id": "event_art", "status": "generated", "scope": "eighteen authored event vignettes", "assets": [row for row in generated if row["kind"] == "event_art"]},
            {"id": "npc_portraits", "status": "generated", "scope": "eight authoritative narrative NPC portraits", "assets": [row for row in generated if row["kind"] == "npc_portraits"]},
            {"id": "ending_art", "status": "generated", "scope": "five authoritative narrative endings", "assets": [row for row in generated if row["kind"] == "ending_art"]},
            {"id": "challenge_rewards", "status": "generated", "scope": "eleven authoritative challenge reward icons", "assets": [row for row in generated if row["kind"] == "challenge_rewards"]},
            {"id": "controls", "status": "generated", "scope": "neutral command symbols", "assets": [row for row in generated if row["kind"] == "controls"]},
            {"id": "items", "status": "generated", "scope": "authoritative item icon atlas", "assets": [row for row in generated if row["kind"] == "items"]},
            {"id": "blessings", "status": "generated", "scope": "authoritative blessing icon atlas", "assets": [row for row in generated if row["kind"] == "blessings"]},
            {"id": "curses", "status": "generated", "scope": "authoritative curse icon atlas", "assets": [row for row in generated if row["kind"] == "curses"]},
            {"id": "talents", "status": "generated", "scope": "authoritative talent icon atlas", "assets": [row for row in generated if row["kind"] == "talents"]},
            {"id": "mode_art", "status": "generated", "scope": "mode entry icon atlas", "assets": [row for row in generated if row["kind"] == "mode_art"]},
            {"id": "final_ui_frames", "status": "generated", "scope": "panel, divider, badge and cursor frame atlas", "assets": [row for row in generated if row["kind"] == "final_ui_frames"]},
            {"id": "font", "status": "vendored", "scope": "OFL licensed Noto Sans SC body and Pixelify Sans Latin display fonts", "assets": fonts},
        ],
        "contact_sheet": "pixel_asset_contact_sheet.png",
        "uncompleted_batches": [],
        "fallbacks": [],
    }
    (destination / "pixel_asset_inventory.json").write_text(json.dumps(inventory, indent=2) + "\n")
    (destination / "LICENSE.txt").write_text(LICENSE)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    generate(parser.parse_args().output)
